/-
  Declaration analysis for extracting atoms from a Lean environment.
-/
import Lean
import ProbeLean.Types
import ProbeLean.Attrs
import ProbeLean.Environment
import ProbeLean.AxiomCheck

namespace ProbeLean

open Lean

/-- Get the display name (last component) of a declaration name -/
def getDisplayName (name : Name) : String :=
  match name with
  | .str _ s => s
  | .num _ n => toString n
  | .anonymous => ""

/-- Check if a string contains a substring -/
def containsSubstring (s : String) (sub : String) : Bool :=
  (s.splitOn sub).length > 1

/-- Auto-generated declaration name suffixes to filter out -/
def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",  -- equation lemmas
  ".mk",  -- constructors
  ".elim",  -- eliminator abbreviations
  ".ctorIdx", ".toCtorIdx"  -- internal ctor index helpers
]

/-- Check if a name is internal (starts with underscore or contains internal markers) -/
def isInternalName (name : Name) : Bool :=
  -- Judge private declarations by their user-facing name (`_private.M.0.Bar.foo`
  -- → `Bar.foo`), so human-written private lemmas survive while private compiler
  -- helpers (`...Bar.foo.match_1`) are still caught. No-op for public names.
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||  -- match statements, etc.
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

/-- Get the module name for a constant in the environment -/
def getModuleName (env : Environment) (name : Name) : Option Name :=
  env.getModuleIdxFor? name >>= fun idx =>
    env.allImportedModuleNames[idx.toNat]?

/-- Whether a module belongs to the project: it is one of `projectModules`, or a
descendant of one. The one place project membership is decided. -/
def isProjectModule (projectModules : Array Name) (modName : Name) : Bool :=
  projectModules.any fun projMod =>
    modName == projMod || modName.toString.startsWith (projMod.toString ++ ".")

/-- Whether a declaration belongs to the project, as a set of module *indices*.

The obvious formulation — resolve the constant's module name, then prefix-match it
against every project module — builds a string per comparison. That is fine once
but it is the dominant cost of extraction in bulk: `getProjectDecls` tests every
constant in the environment (Mathlib included), and `declInfoToAtom` every
dependency occurrence, which on a 190-module project with proof-term dependencies
included runs to tens of thousands. Deciding membership per *module* up front turns
each test into a hash lookup, and made `extract` on SPQR 8× faster. -/
structure ProjectFilter where
  moduleIdxs : Std.HashSet Nat

/-- Precompute the project's module indices. -/
def mkProjectFilter (env : Environment) (projectModules : Array Name) : ProjectFilter :=
  Id.run do
    let names := env.allImportedModuleNames
    let mut idxs : Std.HashSet Nat := {}
    for i in [:names.size] do
      if h : i < names.size then
        if isProjectModule projectModules names[i] then
          idxs := idxs.insert i
    return { moduleIdxs := idxs }

/-- Whether `name` is declared in one of the project's modules. -/
def ProjectFilter.contains (pf : ProjectFilter) (env : Environment) (name : Name) : Bool :=
  match env.getModuleIdxFor? name with
  | some idx => pf.moduleIdxs.contains idx.toNat
  | none => false

/-- Check if a declaration is an auto-named type class instance.
    Lean auto-names instances with an `inst` prefix (e.g., `instAddNat`,
    `instDecidableValidLengths`). User-named instances are not detected
    by this heuristic. -/
def isInstanceName (name : Name) : Bool :=
  match name.componentsRev.head? with
  | some (.str _ s) => s.startsWith "inst"
  | _ => false

/-- Determine the kind of a declaration -/
def getDeclKind (env : Environment) (name : Name) (info : ConstantInfo) : DeclKind :=
  match info with
  | .defnInfo defInfo =>
    if isInstanceName name then
      .instance
    else if env.isProjectionFn name then
      .projection
    else if defInfo.hints.isAbbrev then
      .abbrev
    else
      .def
  | .thmInfo _ => .theorem
  | .inductInfo _ =>
    -- Check if it's a class, structure, or plain inductive
    if Lean.isClass env name then
      .class
    else if Lean.isStructure env name then
      .structure
    else
      .inductive
  | .axiomInfo _ => .axiom
  | .opaqueInfo _ => .opaque
  | .quotInfo _ => .quot
  | .ctorInfo _ => .def  -- Constructors are treated as defs
  | .recInfo _ => .def   -- Recursors are treated as defs

/-- Separated type-level and term-level dependencies of a constant -/
structure DependencyInfo where
  typeDeps : Array Name
  termDeps : Array Name
  all : Array Name

/-- The defining value of a constant: a definition's body, a theorem's proof term,
or an `opaque`'s body.

Reads the field directly instead of calling `ConstantInfo.value?`. That function
gates theorems and `opaque`s behind an `allowOpaque` flag, and its treatment of
theorems changed in Lean 4.30 (`some value` → `if allowOpaque then … else none`).
Because the flag has a default, the change was source-compatible: probe-lean kept
compiling and silently emitted empty `term-dependencies` for **every** theorem on
releases built against Lean ≥ 4.30, which erased all proof edges from the
dependency graph and let `sorry`-tainted theorems be upgraded to
`transitively-verified`. Matching on `ConstantInfo` cannot regress that way.
`AxiomCheck.constChildren` reads the same fields for the same reason. -/
def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  -- Deliberately exhaustive, no wildcard: a future value-bearing
  -- `ConstantInfo` constructor must fail compilation here rather than be
  -- silently dropped the way `value?` silently dropped theorem proofs.
  | .axiomInfo _  => none
  | .quotInfo _   => none
  | .inductInfo _ => none
  | .ctorInfo _   => none
  | .recInfo _    => none

/-- Get the dependencies of a constant, separated into type and term -/
def getDependencies (info : ConstantInfo) : DependencyInfo :=
  let type := info.type
  let value := valueOf info
  let typeConsts := type.getUsedConstants
  let valueConsts := match value with
    | some v => v.getUsedConstants
    | none => #[]
  let all := (typeConsts ++ valueConsts).toList.eraseDups.toArray
  let sortByName (arr : Array Name) := arr.qsort fun a b => a.toString < b.toString
  { typeDeps := sortByName typeConsts, termDeps := sortByName valueConsts, all := sortByName all }

/-- Get source file path for a module (relative to project root).
    Converts component-wise via `moduleNameToRelPath`: rendering the name with
    `Name.toString` would wrap non-identifier components in guillemets
    (`Misc/«Real-EReal-ENNReal».lean`), a path that never exists on disk, so
    such modules would lose their source location (and with it code text,
    source attributes, and sorry matching). -/
def getModuleSourcePath (_env : Environment) (projectPath : System.FilePath) (modName : Name) : IO (Option String) := do
  let some rel := moduleNameToRelPath modName | return none
  let relPath := rel ++ ".lean"
  let fullPath := projectPath / relPath
  if ← fullPath.pathExists then
    return some relPath
  return none

/-- Get declaration source location -/
def getDeclSourceLoc (env : Environment) (name : Name) : Option CodeTextInfo :=
  match declRangeExt.find? env name with
  | some ranges =>
    some {
      linesStart := ranges.range.pos.line
      linesEnd := ranges.range.endPos.line
    }
  | none => none

/-- Extract the source file path from Aeneas docstring `Source: 'path'` pattern -/
def extractSourceFromDocstring (doc : String) : Option String :=
  let pattern := "Source: '"
  let parts := doc.splitOn pattern
  if h : parts.length >= 2 then
    let afterPattern := parts[1]
    let quoteParts := afterPattern.splitOn "'"
    if h2 : quoteParts.length >= 1 then
      some quoteParts[0]
    else none
  else none

/-- Get docstring for a constant from the environment -/
def getDeclDocstring (env : Environment) (name : Name) : IO (Option String) :=
  Lean.findDocString? env name

/-- Get the Rust source path from the docstring of a declaration.
    If no source found and name doesn't end with _body, try the _body variant. -/
def getDeclRustSource (env : Environment) (name : Name) : IO (Option String) := do
  -- First try the declaration itself
  match ← getDeclDocstring env name with
  | some doc =>
    match extractSourceFromDocstring doc with
    | some source => return some source
    | none =>
      -- No source in docstring, try _body variant if applicable
      if !name.toString.endsWith "_body" then
        let bodyName := name.appendAfter "_body"
        if env.find? bodyName |>.isSome then
          match ← getDeclDocstring env bodyName with
          | some bodyDoc => return extractSourceFromDocstring bodyDoc
          | none => return none
        else return none
      else return none
  | none =>
    -- No docstring, try _body variant if applicable
    if !name.toString.endsWith "_body" then
      let bodyName := name.appendAfter "_body"
      if env.find? bodyName |>.isSome then
        match ← getDeclDocstring env bodyName with
        | some bodyDoc => return extractSourceFromDocstring bodyDoc
        | none => return none
      else return none
    else return none

/-- Check if a source path indicates a relevant (crate-internal) function -/
def isRelevantSource (source : Option String) (crate : String) : Bool :=
  match source with
  | none => false  -- No source info -> not relevant
  | some s =>
    -- Must contain crate name and not be from external sources
    containsSubstring s crate &&
    !s.startsWith "/" &&  -- External paths start with /rustc/ or /cargo/
    !containsSubstring s "/cargo/registry/"

-- ============================================================
-- Neutral codomain facts (pure, .olean-derived)
-- Computed here, once, during the environment walk, so an external classifier
-- can reconstruct a declaration's codomain shape from these primitives plus its
-- own catalogue without re-walking the environment.
-- ============================================================

/-- Strip leading `∀`/`→` binders, returning the result type. The body may
contain loose bvars, but head/last-arg inspection does not look inside them. -/
partial def stripForalls : Expr → Expr
  | .forallE _ _ body _ => stripForalls body
  | e => e

/-- The head constant of a declaration's result type, if any. Approximate — it
does not unfold reducible aliases (see the validation gate). -/
def codomainHeadOf (type : Expr) : Option Name :=
  match (stripForalls type).getAppFn with
  | .const n _ => some n
  | _ => none

/-- True when the final application argument of `e` is the constant `Bool`. -/
def lastArgIsBool (e : Expr) : Bool :=
  match e.getAppArgs.back? with
  | some (.const n _) => n == `Bool
  | _ => false

/-- True when the result type (after stripping `∀`/`→` binders) is `Sort 0`, i.e.
a `Prop`. Neutral primitive emitted per atom (independent of any domain
catalogue) so a downstream tool can reconstruct the codomain shape. -/
def codomainIsPropOf (type : Expr) : Bool :=
  match stripForalls type with
  | .sort .zero => true
  | _ => false

/-- Information about a declaration for analysis -/
structure DeclInfo where
  name : Name
  displayName : String
  moduleName : Name
  kind : DeclKind
  dependencies : Array Name
  typeDependencies : Array Name
  termDependencies : Array Name
  sourceInfo : Option CodeTextInfo
  /-- Result-type head constant (approximate; see `codomainHeadOf`). -/
  codomainHead : Option Name := none
  /-- Result type is `Sort 0` (a `Prop`). Neutral primitive (see
      `codomainIsPropOf`). -/
  codomainIsProp : Bool := false
  /-- Final application arg of the result type is `Bool`. Neutral primitive (see
      `lastArgIsBool`). -/
  codomainLastArgIsBool : Bool := false

/-- Analyze a single declaration. -/
def analyzeDecl (env : Environment) (name : Name) (info : ConstantInfo) : DeclInfo :=
  let displayName := getDisplayName name
  let moduleName := getModuleName env name |>.getD .anonymous
  let kind := getDeclKind env name info
  let deps := getDependencies info
  let sourceInfo := getDeclSourceLoc env name
  { name, displayName, moduleName, kind,
    dependencies := deps.all,
    typeDependencies := deps.typeDeps,
    termDependencies := deps.termDeps,
    sourceInfo,
    codomainHead := codomainHeadOf info.type,
    codomainIsProp := codomainIsPropOf info.type,
    codomainLastArgIsBool := lastArgIsBool (stripForalls info.type) }

/-- `outer` covers `inner`'s line range, sharing boundaries allowed but not the
identical range. Ranges are line-only (no columns), so a member reported on the
type's last line counts as covered — which is what we want for a `deriving`
clause that Lean collapses onto the type's final line. -/
def coversRange (outer inner : CodeTextInfo) : Bool :=
  decide (outer.linesStart ≤ inner.linesStart) &&
  decide (inner.linesEnd ≤ outer.linesEnd) &&
  !(inner.linesStart == outer.linesStart && inner.linesEnd == outer.linesEnd)

/-- Names of `deriving`-generated instance clusters (`instDecidableEq…`,
`instRepr…`, plus their backing `.decEq`/`.repr`/… members).

A member qualifies when it is an auto-named `instance` (or a member whose
name-prefix is such an instance) whose source range sits inside an
`inductive`/`structure`/`class` in the same module — i.e. inside that type's
`deriving` clause. Hand-written top-level instances, structure projections, and
proof-fields are excluded.

These names are marked `isLeanGenerated` (see `runAnalysisViaLakeEnv`), **not
dropped**: the atoms stay in the dependency graph so transitive-verification
contamination still flows through them, while `viewify` filters them from the
web UI. Dropping them would be unsound — a surviving theorem depending on such an
instance would lose the contamination path through it and could be falsely
upgraded to `transitively-verified`. -/
def derivedInstanceClusterNames (decls : Array DeclInfo) : Std.HashSet Name := Id.run do
  -- Pre-index type-definition source ranges by module so each `insideTypeDef`
  -- check only scans ranges from the same module, not every type in the project.
  let mut typeRangesByModule : Std.HashMap Name (Array CodeTextInfo) := {}
  for d in decls do
    if d.kind == .inductive || d.kind == .structure || d.kind == .class then
      if let some r := d.sourceInfo then
        typeRangesByModule := typeRangesByModule.insert d.moduleName
          ((typeRangesByModule.getD d.moduleName #[]).push r)
  let insideTypeDef : DeclInfo → Bool := fun d =>
    match d.sourceInfo with
    | none => false
    | some r => (typeRangesByModule.getD d.moduleName #[]).any fun tr => coversRange tr r
  -- Auto-named instances synthesized inside a type definition = deriving output.
  let mut derived : Std.HashSet Name := {}
  for d in decls do
    if d.kind == .instance && insideTypeDef d then
      derived := derived.insert d.name
  -- Backing members of a derived instance (e.g. `instReprPoint.repr`).
  let mut result := derived
  for d in decls do
    if insideTypeDef d && derived.contains d.name.getPrefix then
      result := result.insert d.name
  return result

/-- Names of attribute-macro-generated companion theorems.

Some verification-framework attributes elaborate a tagged theorem into an
extra machine-generated theorem alongside it. The known case is Aeneas's
`@[step]`: for `theorem X`, it adds an mvcgen-shaped wrapper `X.mvcgen_spec`
whose declaration range is registered from the *tagging syntax* — the
inline `@[step]` line, or the `attribute [step] …` command, which can lie
outside `X`'s own range or even tag an external theorem. Via the source-scan
attribute fallback the companion also shows the parent's attributes. Left
untreated, it lands in every dependency's `specs` list next to the real spec
and defeats primary-spec detection (two tagged candidates where the signals
require exactly one).

A theorem named `<parent>.mvcgen_spec` qualifies unless `parent` is known to
be something other than a theorem. The parent's kind is resolved from the
emitted declarations first, then from `externalParentKind` (backed by the
full environment at the call site), so module filtering or an external
parent cannot misclassify. In particular:
- `parent` is a theorem (project or external) → companion (a theorem parent
  is the real spec: project theorems are collected into `specs` themselves);
- `parent` is unresolvable → companion (the name shape is Aeneas generator
  convention);
- `parent` is an **axiom** (project or external) → NOT a companion for our
  purposes: axioms are never collected into `specs` lists, so the wrapper is
  the specified def's only spec-shaped edge — the axiom's proxy. Excluding
  it would orphan every axiom-specified def.

The name shape is the whole signal; two corroborations considered and
rejected: (a) source ranges — the `attribute [step]` command form places the
companion's range outside the parent's, so containment checks reject exactly
the declarations this detection targets; (b) a dependency edge to the parent
— the wrapper references its parent only in the *proof term*. That edge is
observable here (a `DeclInfo`'s `termDependencies` holds raw, unfiltered
names), but requiring it would couple this detection to the generator's proof
shape — the wrapper happens to apply its parent today, and nothing pins that
across Aeneas versions — so the name shape stays the sole signal.
A hand-written theorem that happens to use the name shape is therefore flagged
(accepted false positive: the suffix is Aeneas generator convention, hiding
is mild, and an explicit `@[primary_spec]` tag restores it as primary
spec).

Companions are marked `isAeneasGenerated` + hidden — they exist only because
of Aeneas's attribute machinery, unlike `deriving` clusters and projections,
which are core-Lean output and carry `isLeanGenerated`. Either way they are
**not dropped**: they stay in the dependency graph so transitive-verification
contamination still flows through them. `computeSpecs` excludes generated
theorems (both flags) from spec bookkeeping unless explicitly tagged
`@[primary_spec]`. -/
def generatedCompanionTheoremNames (decls : Array DeclInfo)
    (externalParentKind : Name → Option DeclKind := fun _ => none) :
    Std.HashSet Name := Id.run do
  let mut kindByName : Std.HashMap Name DeclKind := {}
  for d in decls do
    kindByName := kindByName.insert d.name d.kind
  let mut result : Std.HashSet Name := {}
  for d in decls do
    if d.kind == .theorem then
      if let .str parent "mvcgen_spec" := d.name then
        match kindByName.get? parent <|> externalParentKind parent with
        | some .theorem | none => result := result.insert d.name
        | some _ => pure ()
  return result

/-- Get all project declarations from an environment. -/
def getProjectDecls (env : Environment) (projectModules : Array Name)
    (projFilter : ProjectFilter := mkProjectFilter env projectModules) : Array DeclInfo := Id.run do
  let mut decls : Array DeclInfo := #[]
  for (name, info) in env.constants.map₁.toList do
    -- Skip internal names
    if isInternalName name then
      continue
    -- Skip non-project declarations
    if !projFilter.contains env name then
      continue
    -- Skip constructors and recursors (they'll be covered by their parent type)
    match info with
    | .ctorInfo _ => continue
    | .recInfo _ => continue
    | _ => pure ()
    let decl := analyzeDecl env name info
    -- Skip declarations without source location (auto-generated by the kernel)
    if decl.sourceInfo.isNone then
      continue
    decls := decls.push decl
  -- Sort by declaration name for deterministic output (P14)
  decls.qsort fun a b => a.name.toString < b.name.toString

/-- File content cache to avoid re-reading the same file for every declaration. -/
abbrev FileCache := IO.Ref (Std.HashMap String (Array String))

/-- Read a file's lines, using the cache. -/
def readFileLines (cache : FileCache) (path : String) : IO (Array String) := do
  let map ← cache.get
  if let some lines := map[path]? then
    return lines
  let content ← IO.FS.readFile ⟨path⟩
  let lines := content.splitOn "\n" |>.toArray
  cache.modify fun m => m.insert path lines
  return lines

/-- Parse attribute names out of a single `@[...]` block's inner content.
    E.g. `"progress, externally_verified"` → `#["progress", "externally_verified"]`. -/
private def parseAttrBlock (inside : String) : Array String := Id.run do
  let mut result : Array String := #[]
  for part in inside.splitOn "," do
    let trimmed := part.trimAscii.toString
    let attrName := (trimmed.splitOn " ").head!.trimAscii.toString
    if !attrName.isEmpty then
      result := result.push attrName
  return result

/-- Extract all `@[...]` blocks from a single line and return attribute names. -/
private def extractAttrsFromLine (line : String) : Array String := Id.run do
  let mut result : Array String := #[]
  -- Split on "@[" to find each block
  let parts := line.splitOn "@["
  -- First element is text before any @[, skip it
  for i in [1:parts.length] do
    let segment := parts[i]!
    -- Find the closing "]"
    let bracketParts := segment.splitOn "]"
    if bracketParts.length >= 1 then
      let inside := bracketParts[0]!
      for attr in parseAttrBlock inside do
        if !result.contains attr then
          result := result.push attr
  return result

/-- Extract attribute names from source text around a declaration.
    Scans from `startLine` (0-based, typically the docstring) through `endLine`
    for `@[...]` annotations. Stops at the declaration keyword. -/
def extractAttributesFromSource (cache : FileCache) (projectPath : System.FilePath)
    (codePath : String) (startLine endLine : Nat) : IO (Array String) := do
  if codePath.isEmpty then return #[]
  let fullPath := (projectPath / codePath).toString
  let lines ← readFileLines cache fullPath
  if lines.isEmpty then return #[]

  let mut attrs : Array String := #[]
  -- Scan from declaration range start through the end, looking for @[...] blocks.
  -- The range starts at the docstring; attributes appear between the docstring and
  -- the theorem/def keyword.
  let scanFrom := if startLine > 2 then startLine - 2 else 0
  let scanTo := min (endLine + 1) lines.size

  for i in [scanFrom:scanTo] do
    if h : i < lines.size then
      let line := lines[i]
      for attr in extractAttrsFromLine line do
        if !attrs.contains attr then
          attrs := attrs.push attr
  return attrs

/-- Strip leading "./" from a path string -/
def stripLeadingDotSlash (path : String) : String :=
  -- Replace multiple ./ patterns at the start
  let path := path.replace "././././" ""
  let path := path.replace "././" ""
  if path.startsWith "./" then (path.drop 2).toString else path

-- ============================================================
-- Auxiliary-dependency folding (issue #99)
--
-- Lean abstracts non-atomic embedded proofs and match arms into auxiliary
-- constants (`X._proof_N`, `X.match_N`, tactic-generated helpers). probe-lean
-- filters those out of its output (`isInternalName`), which used to lose every
-- edge underneath them: `host → aux → lemma` left no trace of `lemma`.
--
-- The fold is a strictly **additive** second pass. Governing invariant, stated
-- once in `docs/SCHEMA.md` ("Auxiliary-dependency folding") and not restated
-- elsewhere:
--
--   It only ever *adds* names to `term-dependencies`. It never adds to
--   `type-dependencies`, never removes an entry from any of the four dependency
--   arrays, never adds to the `*-external` arrays, and never changes the atom
--   set.
--
-- `partitionDeps` keeps its behaviour byte-for-byte; the fold runs after it and
-- appends. Consequently edges to emitted project axioms/inductives/structures
-- and direct external anchors cannot be lost — their routing is never consulted.
-- ============================================================

/-- How the auxiliary-fold pass treats one dependency occurrence. -/
inductive DepClass where
  /-- A fold *target*: a project constant that survives the name filter and has
      a declaration range. Collected, never traversed through (so the fold does
      not flatten a host's graph past its real dependencies).

      That is every atom **plus named inductive constructors**: `getProjectDecls`
      additionally skips `.ctorInfo`/`.recInfo`, which this classifier does not
      mirror, so a project `Color.red` is a target while never being emitted as
      an atom of its own. Benign, and identical to how a *direct* edge to such a
      constructor already behaves (`partitionMissingDeps` treats a constructor
      whose parent type is extracted as benign) — but "targets are exactly the
      atoms" is false, and `docs/SCHEMA.md` says so too. -/
  | emitted
  /-- Not emitted as an atom, value-bearing, not a structural member: traversed
      through, contributing whatever it reaches. -/
  | foldable
  /-- Neither a target nor traversable: constants outside the project filter
      *that survive the name filter*, structural members (`.mk`, `.injEq`,
      `.casesOn`, …), and non-value-bearing constants with no declaration range
      (axioms, inductives, constructors, recursors, `Quot`).

      Two boundaries worth stating, because neither is what the short form
      suggests. A *project* axiom or inductive with a range is `.emitted`, not
      `.ignored`. And "outside the project filter" is not sufficient on its own:
      an external constant the name filter drops (a Mathlib or core `_proof_N` /
      `match_N`) is value-bearing and `.foldable`, so it is traversed — only the
      *targets* collected are project-internal. That is deliberate. Under a
      module-prefix filter a non-project module can sit between two filtered
      modules, and an edge through its auxiliary is then genuinely recoverable.

      "Not foldable" is different from "not an edge" — but it is not "edge
      preserved" either, and which applies is decided by the name filter rather
      than by anything here. A direct reference that survives `isInternalName`
      stays in its project or `*-external` bucket as always; one the name filter
      catches (every structural-member suffix, every recursor) is dropped from
      all four arrays by `partitionDeps`, also as always. Constructors split on
      that same rule, not as a class: `Color.red` is kept, `Foo.mk` is not. -/
  | ignored
  /-- `env.find?` failed. Not silently dropped: reported once per extraction. -/
  | unresolved
  deriving DecidableEq, Repr, Inhabited

/-- Whether `name` is a structural member of a type rather than a term/proof
abstraction. Tested as a **string** suffix, the convention `isInternalName`
uses: `autoGeneratedSuffixes` holds multi-component entries like `.mk.injEq`, so
a last-component test is the wrong primitive.

Structural members are deliberately *not* folded through — mapping them to their
parent atom is a separate concern (they are members of an emitted type, not
hidden proof terms). -/
def isStructuralMemberName (name : Name) : Bool :=
  let str := (Lean.privateToUserName name).toString
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

/-- Classify one dependency occurrence for the fold.

`env.find?` is consulted **first**, before any name or kind test, so a missing
`Missing.mk` is reported as unresolved rather than silently dropped by suffix.

`isProjectMember` is passed as a predicate rather than a `ProjectFilter` so the
classifier is exercisable against a real `Environment` in tests (locally
elaborated constants have no module index) and so "restricted-library
extraction" — a narrower project set — is expressible. In production it is
`projFilter.contains env`. -/
def classifyFoldCandidate (env : Environment) (isProjectMember : Name → Bool)
    (n : Name) : DepClass :=
  match env.find? n with
  | none => .unresolved
  | some info =>
    let isProj := isProjectMember n
    -- Not emitted as an atom: dropped by name (`isInternalName`), or a project
    -- member the environment walk skips for having no declaration range.
    let notEmitted := isInternalName n || (isProj && (declRangeExt.find? env n).isNone)
    if notEmitted then
      if isStructuralMemberName n then .ignored
      else
        -- Exhaustive over `ConstantInfo` via `valueOf` (no wildcard), so a
        -- future value-bearing constructor fails compilation rather than being
        -- silently skipped.
        match valueOf info with
        | some _ => .foldable
        | none   => .ignored
    else if isProj then .emitted
    else .ignored

/-- Cross-root state for the auxiliary-fold traversal.

`cache` holds only **complete** closures (rule 4 in `foldedDeps`), keyed to one
immutable `Environment` and one classification policy. Extraction is sequential
and builds one state per run — that is the cache's stated invariant, not a
silent assumption. Cached closures are project-filtered but **not**
host-filtered: self-edge suppression happens at the host merge, so a closure
shared by two hosts stays correct for both.

-/
structure FoldState where
  /-- Complete, project-filtered, deduplicated closures, by node. -/
  cache : Std.HashMap Name (Array Name) := {}
  /-- Per-root visited set. Reset by `foldedDepsFrom` for each closure query. -/
  visited : Std.HashSet Name := {}
  /-- Names `env.find?` could not resolve, deduplicated for one report. -/
  unresolved : Std.HashSet Name := {}
  /-- Node expansions (performance gate). -/
  expansions : Nat := 0
  /-- Edges scanned (performance gate). -/
  edgesScanned : Nat := 0
  /-- Revisits suppressed because the node was already visited in this root
      query and had no cached complete closure — i.e. how often rule 2 fired.
      Not a count of incomplete expansions: one expansion can suppress several
      revisits, and an expansion that is incomplete only because a descendant
      was does not appear here. Nor is every suppression an active back-edge; the
      skipped node may be one that already completed without becoming cacheable.
      Reported, because a run where this stays 0 has not exercised the cycle
      rules at all. -/
  nonCacheable : Nat := 0
  /-- Dependency entries the fold added (the recovered edges). -/
  addedEdges : Nat := 0

/-- A traversal policy: the out-edges to follow and how to classify what they
reach. Bundling the two means a caller cannot supply a `children` from one policy
and a `classify` from another.

It does **not** tie the policy to a `FoldState`: a cached closure is only valid
for the walk that built it, but that is an invariant the caller upholds, not one
the types enforce — `foldedDepsFrom` takes the walk and the state independently.
The single production caller establishes it by building one state per extraction
run alongside one walk (`ProbeLean/Atomize.lean`). -/
structure FoldWalk where
  children : Name → Array Name
  classify : Name → DepClass

/-- The production traversal policy: full reachability (`constChildren`, i.e. a
node's type *and* value constants) under the project filter. -/
def FoldWalk.ofEnv (env : Environment) (isProjectMember : Name → Bool) : FoldWalk :=
  { children := constChildren env
    classify := classifyFoldCandidate env isProjectMember }

/-- Deduplicate and sort names by their string form, the project's determinism
convention (P14). -/
def sortDedupNames (arr : Array Name) : Array Name :=
  let s : Std.HashSet Name := arr.foldl (init := {}) fun s n => s.insert n
  s.toArray.qsort fun a b => a.toString < b.toString

/-- Project-emitted constants reachable from `n` through foldable nodes only.

Returns `(targets, cacheable)`. `cacheable := false` when the result was
computed across a skipped back-edge and may therefore be incomplete. A *root*
result is always complete (DFS collects every discovered node's emitted children
and propagates them up the discovery tree); only intermediate frames can be
partial, which is exactly what the flag records.

Four rules:

1. **Per-root visited set** bounds one traversal to a bounded number of node
   expansions. Without it, a cyclic region where every branch hits a back-edge
   and nothing is cacheable can enumerate exponentially many paths through a
   linear-size graph. Visitation resets for each independent closure query
   (`foldedDepsFrom`) — sharing it across queries would let one query's
   suppressions silently truncate the next.
2. **Every visited-set suppression returns non-cacheable**, after a complete
   cached result has been checked for, and whether the skipped node is still
   active or has already completed without being cacheable. Otherwise a node
   that completed incompletely could be re-read as an authoritative empty
   result by a later sibling.
3. **Cacheability propagates transitively**: an ancestor that consumed an
   incomplete result is itself incomplete and must stay out of the cache.
   Suppressing caching only in the detecting frame is not enough.
4. **The cache stores only `cacheable` results**, project-filtered and
   deduplicated during construction.

Generic over `children`/`classify` so the traversal is unit-testable without an
`Environment`.

On reachability: a cycle in `constChildren`'s raw graph is not enough to exercise
any of this, because every node on it must also classify `.foldable`. `Foo →
Foo.mk → Foo` — the obvious candidate — cannot be entered at all: `Foo.mk` ends
with a `autoGeneratedSuffixes` entry, so `isStructuralMemberName` sends it to
`.ignored`. A self-recursive internal-named definition does reach it, e.g.

    unsafe def _foldCycle (arg : Nat) : Nat := _foldCycle arg

which is `.foldable` and appears among its own children. No *naturally occurring*
instance has been observed yet: `FoldState.nonCacheable` was 0 across
curve25519-dalek-lean-verify, which is why `extract` reports that counter. So the
rules below are a termination guarantee for a shape the traversal admits, not a
response to a measured one. -/
private partial def foldedDepsCore (w : FoldWalk) (n : Name) :
    StateM FoldState (Array Name × Bool) := do
  if let some hit := (← get).cache[n]? then
    return (hit, true)
  if (← get).visited.contains n then
    modify fun s => { s with nonCacheable := s.nonCacheable + 1 }
    return (#[], false)
  let kids := w.children n
  modify fun s => { s with
    visited := s.visited.insert n
    expansions := s.expansions + 1
    edgesScanned := s.edgesScanned + kids.size }
  let mut acc : Array Name := #[]
  let mut cacheable := true
  for ch in kids do
    match w.classify ch with
    | .emitted => acc := acc.push ch
    | .foldable =>
      let (sub, subCacheable) ← foldedDepsCore w ch
      acc := acc ++ sub
      unless subCacheable do cacheable := false
    | .unresolved => modify fun s => { s with unresolved := s.unresolved.insert ch }
    | .ignored => pure ()
  let targets := sortDedupNames acc
  if cacheable then
    modify fun s => { s with cache := s.cache.insert n targets }
  return (targets, cacheable)

/-- One independent closure query: `foldedDepsCore` with a fresh per-root visited
set (rule 1). This is the **only** entry point — the recursive worker is private
because calling it on an already-used state silently truncates any
visited-but-uncached node, and that is exactly the cyclic case.

A root's result is always complete, so the cacheability flag (internal
bookkeeping) is not returned. -/
def foldedDepsFrom (w : FoldWalk) (n : Name) : StateM FoldState (Array Name) := do
  modify fun s => { s with visited := {} }
  let (targets, _) ← foldedDepsCore w n
  return targets

/-- Union of the closures of every foldable occurrence in `raw`. Unresolved
occurrences are recorded rather than dropped. -/
def foldOccurrences (w : FoldWalk) (raw : Array Name) : StateM FoldState (Array Name) := do
  let mut acc : Array Name := #[]
  for d in raw do
    match w.classify d with
    | .foldable => acc := acc ++ (← foldedDepsFrom w d)
    | .unresolved => modify fun s => { s with unresolved := s.unresolved.insert d }
    | _ => pure ()
  return acc

/-- Additive fold of one dependency list.

`raw` is the declaration's unfiltered dependency occurrences; `proj` is what
`partitionDeps` already produced for that list. Every foldable occurrence — the
internal names `partitionDeps` dropped, plus project members it kept that are
not emitted as atoms — is traversed, and the targets are **appended** to `proj`.
Nothing is removed or rerouted, so a dangling direct edge to a non-emitted
project name is kept *as well as* folded and the missing-dependency warning
still fires.

`host` is dropped from the folded targets (`H → aux → H` is not a self-loop the
graph needs); suppression is per-host and never enters the cache. -/
def mergeFolded (host : Name) (proj extra : Array Name) :
    StateM FoldState (Array Name) := do
  if extra.isEmpty then return proj
  let merged := sortDedupNames (proj ++ extra.filter (· != host))
  modify fun s => { s with addedEdges := s.addedEdges + (merged.size - proj.size) }
  return merged

/-- `foldOccurrences` followed by `mergeFolded`: the whole additive fold of one
dependency list under a single scope. -/
def foldDepList (w : FoldWalk) (host : Name) (raw : Array Name) (proj : Array Name) :
    StateM FoldState (Array Name) := do
  mergeFolded host proj (← foldOccurrences w raw)

/-- The fold state, shared across one extraction run. -/
abbrev AuxDepCache := IO.Ref FoldState

/-- Fold one declaration's type and term dependency lists, and recompute the
`dependencies` union from the folded results.

`dependencies` is documented as the deduplicated union of `type-dependencies`
and `term-dependencies`, and is now derived here from the folded arrays. It used
to be computed independently, by filtering `info.dependencies` with its own copy
of the project-membership test; that produced the same set only because the copy
and `partitionDeps` classified identically. Deriving the union from the arrays it
is documented to be the union of removes that coupling, and
`tools/audit/compare-extract.py` asserts the identity on real output so a future
divergence fails loudly instead of dropping entries. -/
def foldAtomDeps (env : Environment) (isProjectMember : Name → Bool)
    (auxCache : AuxDepCache) (info : DeclInfo)
    (projTypeDeps projTermDeps : Array Name) :
    IO (Array Name × Array Name × Array Name) := do
  let walk := FoldWalk.ofEnv env isProjectMember
  let act : StateM FoldState (Array Name × Array Name × Array Name) := do
    -- Recovered edges all land in `term-dependencies`, including those found
    -- under an auxiliary the *type* named. `type-dependencies` therefore stays
    -- exactly what `partitionDeps` produced — syntactically what the signature
    -- mentions — so the fold leaves *type-driven* spec selection untouched:
    -- `computeSpecs` walks that array to decide what a theorem specifies.
    --
    -- It is not a blanket "`specs` cannot change" guarantee. `specTargets`
    -- (`ProbeLean/Atomize.lean`) has one fallback that reads the union
    -- `dependencies`: a `@[primary_spec]`-tagged theorem whose statement names
    -- nothing specifiable. A folded *term* edge can add a second candidate
    -- there and detach the tag with `type-dependencies` byte-identical — see
    -- `testPrimarySpecFoldFallback` in `Tests/Main.lean`.
    --
    -- The alternative (route a type-position auxiliary's *type* reach into the
    -- type bucket, its *value* reach into the term bucket) was implemented and
    -- measured: it needs a third traversal per declaration under a second cache
    -- partition, and cost +54% extract wall-clock on a 2354-atom project against
    -- a +2 s budget, to move 4 edges. A folded edge is indirect by construction,
    -- so the bucket whose consumers tolerate indirection is the right home for
    -- all of them; `dependencies` (the union) carries them either way, which is
    -- what verification-status propagation reads.
    let fromType ← foldOccurrences walk info.typeDependencies
    let fromTerm ← foldOccurrences walk info.termDependencies
    let foldedTerm ← mergeFolded info.name projTermDeps (fromType ++ fromTerm)
    return (sortDedupNames (projTypeDeps ++ foldedTerm), projTypeDeps, foldedTerm)
  let st ← auxCache.get
  let (result, st) := act.run st
  auxCache.set st
  return result

/-- Convert a DeclInfo to an Atom -/
def declInfoToAtom (env : Environment) (projectPath : System.FilePath) (projFilter : ProjectFilter) (crate : String) (fileCache : FileCache) (auxCache : AuxDepCache) (info : DeclInfo) : IO Atom := do
  let sourcePathStr ← match info.sourceInfo with
    | some _ =>
      let sourcePath ← getModuleSourcePath env projectPath info.moduleName
      pure (match sourcePath with
        | some p => stripLeadingDotSlash p
        | none => "")
    | none => pure ""

  -- External (non-project) deps: referenced but outside the project (Mathlib,
  -- core). Emitted alongside the project-filtered deps so a downstream
  -- classifier can reconstruct the full reachability graph (it needs edges to
  -- external anchors that `projTypeDeps`/`projTermDeps` drop).
  --
  -- Partitioned in one pass per list rather than filtered once per output array:
  -- `isInternalName` scans the name and the module lookup hashes it, and with
  -- proof terms included these lists run to tens of thousands of entries per
  -- project. Input order is preserved, so both outputs stay name-sorted (P14).
  let partitionDeps (deps : Array Name) : Array Name × Array Name :=
    deps.foldl (init := (#[], #[])) fun (proj, ext) dep =>
      if isInternalName dep then (proj, ext)
      else if projFilter.contains env dep then (proj.push dep, ext)
      else (proj, ext.push dep)

  let (directProjTypeDeps, extTypeDeps) := partitionDeps info.typeDependencies
  let (directProjTermDeps, extTermDeps) := partitionDeps info.termDependencies

  -- Additive auxiliary fold (issue #99): recover the project edges hidden under
  -- non-emitted auxiliaries. `ext*` above are already final — the fold never
  -- touches them (see the `DepClass` invariant note).
  let (projDeps, projTypeDeps, projTermDeps) ←
    foldAtomDeps env (projFilter.contains env) auxCache info
      directProjTypeDeps directProjTermDeps

  let rustSource ← getDeclRustSource env info.name
  let isRelevant := if crate.isEmpty then true else isRelevantSource rustSource crate
  let isPrimarySpec := primarySpecAttr.hasTag env info.name
  let isExternallyVerified := externallyVerifiedAttr.hasTag env info.name

  -- Handle-based detection (works when target imports ProbeLean.Attrs)
  let mut attrs : Array String := #[]
  if isPrimarySpec then
    attrs := attrs.push "primary_spec"
  if isExternallyVerified then
    attrs := attrs.push "externally_verified"

  -- Source-level fallback: scan the .lean file for @[...] annotations
  let startLine := info.sourceInfo.map (·.linesStart) |>.getD 0
  let endLine := info.sourceInfo.map (·.linesEnd) |>.getD startLine
  let sourceAttrs ← extractAttributesFromSource fileCache projectPath sourcePathStr startLine endLine
  for sa in sourceAttrs do
    if !attrs.contains sa then
      attrs := attrs.push sa

  let sortedAttrs := attrs.qsort (· < ·)
  return {
    name := probeRef info.name
    displayName := info.displayName
    dependencies := projDeps.map probeRef
    typeDependencies := projTypeDeps.map probeRef
    termDependencies := projTermDeps.map probeRef
    typeDependenciesExternal := extTypeDeps.map probeRef
    termDependenciesExternal := extTermDeps.map probeRef
    codeModule := info.moduleName.toString
    codePath := sourcePathStr
    codeText := if sourcePathStr.isEmpty then none else info.sourceInfo
    kind := info.kind
    isRelevant := isRelevant
    isInPackage := true
    rustSource := rustSource
    attributes := sortedAttrs
    isPrimarySpec := isPrimarySpec
    codomainHead := info.codomainHead.map (·.toString)
    codomainIsProp := info.codomainIsProp
    codomainLastArgIsBool := info.codomainLastArgIsBool
  }

end ProbeLean
