/-
  Declaration analysis for extracting atoms from a Lean environment.
-/
import Lean
import ProbeLean.Types
import ProbeLean.Attrs
import ProbeLean.Environment
import ProbeLean.AxiomCheck
import ProbeLean.Trust

namespace ProbeLean

open Lean

/-- Get the display name (last component) of a declaration name -/
def getDisplayName (name : Name) : String :=
  match name with
  | .str _ s => s
  | .num _ n => toString n
  | .anonymous => ""

/-- Check if a string contains a substring -/
def containsSubstring (s : String) (sub : String) : Bool :=
  (s.splitOn sub).length > 1

/-- Auto-generated declaration name suffixes to filter out -/
def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",  -- equation lemmas
  ".mk",  -- constructors
  ".elim",  -- eliminator abbreviations
  ".ctorIdx", ".toCtorIdx"  -- internal ctor index helpers
]

/-- Check if a name is internal (starts with underscore or contains internal markers) -/
def isInternalName (name : Name) : Bool :=
  -- Judge private declarations by their user-facing name (`_private.M.0.Bar.foo`
  -- → `Bar.foo`), so human-written private lemmas survive while private compiler
  -- helpers (`...Bar.foo.match_1`) are still caught. No-op for public names.
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||  -- match statements, etc.
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

/-- The module name of a constant, against a module-name array fetched once.
    `Environment.allImportedModuleNames` *builds* its array on every call
    (`header.modules.map (·.module)`, ~3000 entries on a Mathlib-backed project), so a
    per-constant loop fetches it once and passes it here. -/
def moduleNameOf (modNames : Array Name) (env : Environment) (name : Name) : Option Name :=
  env.getModuleIdxFor? name >>= fun idx => modNames[idx.toNat]?

/-- Whether a module belongs to the project: it is one of `projectModules`, or a
descendant of one. The one place project membership is decided. -/
def isProjectModule (projectModules : Array Name) (modName : Name) : Bool :=
  -- Component-wise ancestry (`Name.isPrefixOf`): equal, or a descendant. No
  -- allocation per pair — the string form (`toString.startsWith (toString ++ ".")`)
  -- cost two allocations for each of the ~3000 × 260 (environment module × project
  -- module) pairs, 0.4–0.9 s per `mkProjectFilter`. On degenerate names the two
  -- differ: `.anonymous` is a structural prefix of every module, and a single
  -- component whose printed form contains `.` (through `«…»` escaping) is not a
  -- structural descendant. Path-derived module names hit neither.
  projectModules.any fun projMod => projMod.isPrefixOf modName

/-- Whether a declaration belongs to the project, as a set of module *indices*.

The obvious formulation — resolve the constant's module name, then prefix-match it
against every project module — builds a string per comparison. That is fine once
but it is the dominant cost of extraction in bulk: `declInfoToAtom` tests every
dependency occurrence of every emitted declaration, which on a 190-module project
with proof-term dependencies included runs to tens of thousands. Deciding
membership per *module* up front turns each test into a hash lookup, and made
`extract` on SPQR 8× faster. The per-module test itself (`isProjectModule`) is
allocation-free too, so building a filter costs milliseconds. -/
structure ProjectFilter where
  moduleIdxs : Std.HashSet Nat

/-- Precompute the project's module indices. -/
def mkProjectFilter (env : Environment) (projectModules : Array Name) : ProjectFilter :=
  Id.run do
    let names := env.allImportedModuleNames
    let mut idxs : Std.HashSet Nat := {}
    for i in [:names.size] do
      if h : i < names.size then
        if isProjectModule projectModules names[i] then
          idxs := idxs.insert i
    return { moduleIdxs := idxs }

/-- Whether `name` is declared in one of the project's modules. -/
def ProjectFilter.contains (pf : ProjectFilter) (env : Environment) (name : Name) : Bool :=
  match env.getModuleIdxFor? name with
  | some idx => pf.moduleIdxs.contains idx.toNat
  | none => false

/-- Check if a declaration is an auto-named type class instance.
    Lean auto-names instances with an `inst` prefix (e.g., `instAddNat`,
    `instDecidableValidLengths`). User-named instances are not detected
    by this heuristic. -/
def isInstanceName (name : Name) : Bool :=
  match name.componentsRev.head? with
  | some (.str _ s) => s.startsWith "inst"
  | _ => false

/-- Determine the kind of a declaration -/
def getDeclKind (env : Environment) (name : Name) (info : ConstantInfo) : DeclKind :=
  match info with
  | .defnInfo defInfo =>
    if isInstanceName name then
      .instance
    else if env.isProjectionFn name then
      .projection
    else if defInfo.hints.isAbbrev then
      .abbrev
    else
      .def
  | .thmInfo _ => .theorem
  | .inductInfo _ =>
    -- Check if it's a class, structure, or plain inductive
    if Lean.isClass env name then
      .class
    else if Lean.isStructure env name then
      .structure
    else
      .inductive
  | .axiomInfo _ => .axiom
  | .opaqueInfo _ => .opaque
  | .quotInfo _ => .quot
  | .ctorInfo _ => .def  -- Constructors are treated as defs
  | .recInfo _ => .def   -- Recursors are treated as defs

/-- Separated type-level and term-level dependencies of a constant -/
structure DependencyInfo where
  typeDeps : Array Name
  termDeps : Array Name
  all : Array Name

/-- The defining value of a constant: a definition's body, a theorem's proof term,
or an `opaque`'s body.

Reads the field directly instead of calling `ConstantInfo.value?`. That function
gates theorems and `opaque`s behind an `allowOpaque` flag, and its treatment of
theorems changed in Lean 4.30 (`some value` → `if allowOpaque then … else none`).
Because the flag has a default, the change was source-compatible: probe-lean kept
compiling and silently emitted empty `term-dependencies` for **every** theorem on
releases built against Lean ≥ 4.30, which erased all proof edges from the
dependency graph and let `sorry`-tainted theorems be upgraded to
`transitively-verified`. Matching on `ConstantInfo` cannot regress that way.
`AxiomCheck.constChildren` reads the same fields for the same reason. -/
def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  -- Deliberately exhaustive, no wildcard: a future value-bearing
  -- `ConstantInfo` constructor must fail compilation here rather than be
  -- silently dropped the way `value?` silently dropped theorem proofs.
  | .axiomInfo _  => none
  | .quotInfo _   => none
  | .inductInfo _ => none
  | .ctorInfo _   => none
  | .recInfo _    => none

/-- Get the dependencies of a constant, separated into type and term -/
def getDependencies (info : ConstantInfo) : DependencyInfo :=
  let type := info.type
  let value := valueOf info
  let typeConsts := type.getUsedConstants
  let valueConsts := match value with
    | some v => v.getUsedConstants
    | none => #[]
  let all := (typeConsts ++ valueConsts).toList.eraseDups.toArray
  let sortByName (arr : Array Name) := arr.qsort fun a b => a.toString < b.toString
  { typeDeps := sortByName typeConsts, termDeps := sortByName valueConsts, all := sortByName all }

/-- Get source file path for a module (relative to project root).
    Converts component-wise via `moduleNameToRelPath`: rendering the name with
    `Name.toString` would wrap non-identifier components in guillemets
    (`Misc/«Real-EReal-ENNReal».lean`), a path that never exists on disk, so
    such modules would lose their source location (and with it code text,
    source attributes, and sorry matching). -/
def getModuleSourcePath (_env : Environment) (projectPath : System.FilePath) (modName : Name) : IO (Option String) := do
  let some rel := moduleNameToRelPath modName | return none
  let relPath := rel ++ ".lean"
  let fullPath := projectPath / relPath
  if ← fullPath.pathExists then
    return some relPath
  return none

/-- Get declaration source location -/
def getDeclSourceLoc (env : Environment) (name : Name) : Option CodeTextInfo :=
  match declRangeExt.find? env name with
  | some ranges =>
    some {
      linesStart := ranges.range.pos.line
      linesEnd := ranges.range.endPos.line
    }
  | none => none

/-- Extract the source file path from Aeneas docstring `Source: 'path'` pattern -/
def extractSourceFromDocstring (doc : String) : Option String :=
  let pattern := "Source: '"
  let parts := doc.splitOn pattern
  if h : parts.length >= 2 then
    let afterPattern := parts[1]
    let quoteParts := afterPattern.splitOn "'"
    if h2 : quoteParts.length >= 1 then
      some quoteParts[0]
    else none
  else none

/-- Get docstring for a constant from the environment -/
def getDeclDocstring (env : Environment) (name : Name) : IO (Option String) :=
  Lean.findDocString? env name

/-- Get the Rust source path from the docstring of a declaration.
    If no source found and name doesn't end with _body, try the _body variant. -/
def getDeclRustSource (env : Environment) (name : Name) : IO (Option String) := do
  -- First try the declaration itself
  match ← getDeclDocstring env name with
  | some doc =>
    match extractSourceFromDocstring doc with
    | some source => return some source
    | none =>
      -- No source in docstring, try _body variant if applicable
      if !name.toString.endsWith "_body" then
        let bodyName := name.appendAfter "_body"
        if env.find? bodyName |>.isSome then
          match ← getDeclDocstring env bodyName with
          | some bodyDoc => return extractSourceFromDocstring bodyDoc
          | none => return none
        else return none
      else return none
  | none =>
    -- No docstring, try _body variant if applicable
    if !name.toString.endsWith "_body" then
      let bodyName := name.appendAfter "_body"
      if env.find? bodyName |>.isSome then
        match ← getDeclDocstring env bodyName with
        | some bodyDoc => return extractSourceFromDocstring bodyDoc
        | none => return none
      else return none
    else return none

/-- Check if a source path indicates a relevant (crate-internal) function -/
def isRelevantSource (source : Option String) (crate : String) : Bool :=
  match source with
  | none => false  -- No source info -> not relevant
  | some s =>
    -- Must contain crate name and not be from external sources
    containsSubstring s crate &&
    !s.startsWith "/" &&  -- External paths start with /rustc/ or /cargo/
    !containsSubstring s "/cargo/registry/"

-- ============================================================
-- Neutral codomain facts (pure, .olean-derived)
-- Computed here, once, during the environment walk, so an external classifier
-- can reconstruct a declaration's codomain shape from these primitives plus its
-- own catalogue without re-walking the environment.
-- ============================================================

/-- Strip leading `∀`/`→` binders, returning the result type. The body may
contain loose bvars, but head/last-arg inspection does not look inside them. -/
partial def stripForalls : Expr → Expr
  | .forallE _ _ body _ => stripForalls body
  | e => e

/-- The head constant of a declaration's result type, if any. Approximate — it
does not unfold reducible aliases (see the validation gate). -/
def codomainHeadOf (type : Expr) : Option Name :=
  match (stripForalls type).getAppFn with
  | .const n _ => some n
  | _ => none

/-- True when the final application argument of `e` is the constant `Bool`. -/
def lastArgIsBool (e : Expr) : Bool :=
  match e.getAppArgs.back? with
  | some (.const n _) => n == `Bool
  | _ => false

/-- True when the result type (after stripping `∀`/`→` binders) is `Sort 0`, i.e.
a `Prop`. Neutral primitive emitted per atom (independent of any domain
catalogue) so a downstream tool can reconstruct the codomain shape. -/
def codomainIsPropOf (type : Expr) : Bool :=
  match stripForalls type with
  | .sort .zero => true
  | _ => false

/-- Information about a declaration for analysis -/
structure DeclInfo where
  name : Name
  displayName : String
  moduleName : Name
  kind : DeclKind
  dependencies : Array Name
  typeDependencies : Array Name
  termDependencies : Array Name
  sourceInfo : Option CodeTextInfo
  /-- Result-type head constant (approximate; see `codomainHeadOf`). -/
  codomainHead : Option Name := none
  /-- Result type is `Sort 0` (a `Prop`). Neutral primitive (see
      `codomainIsPropOf`). -/
  codomainIsProp : Bool := false
  /-- Final application arg of the result type is `Bool`. Neutral primitive (see
      `lastArgIsBool`). -/
  codomainLastArgIsBool : Bool := false

/-- Analyze a single declaration. `modNames` is `env.allImportedModuleNames`, fetched
    once by the caller (see `moduleNameOf`). -/
def analyzeDecl (env : Environment) (modNames : Array Name) (name : Name) (info : ConstantInfo)
    : DeclInfo :=
  let displayName := getDisplayName name
  let moduleName := moduleNameOf modNames env name |>.getD .anonymous
  let kind := getDeclKind env name info
  let deps := getDependencies info
  let sourceInfo := getDeclSourceLoc env name
  { name, displayName, moduleName, kind,
    dependencies := deps.all,
    typeDependencies := deps.typeDeps,
    termDependencies := deps.termDeps,
    sourceInfo,
    codomainHead := codomainHeadOf info.type,
    codomainIsProp := codomainIsPropOf info.type,
    codomainLastArgIsBool := lastArgIsBool (stripForalls info.type) }

/-- `outer` covers `inner`'s line range, sharing boundaries allowed but not the
identical range. Ranges are line-only (no columns), so a member reported on the
type's last line counts as covered — which is what we want for a `deriving`
clause that Lean collapses onto the type's final line. -/
def coversRange (outer inner : CodeTextInfo) : Bool :=
  decide (outer.linesStart ≤ inner.linesStart) &&
  decide (inner.linesEnd ≤ outer.linesEnd) &&
  !(inner.linesStart == outer.linesStart && inner.linesEnd == outer.linesEnd)

/-- Names of `deriving`-generated instance clusters (`instDecidableEq…`,
`instRepr…`, plus their backing `.decEq`/`.repr`/… members).

A member qualifies when it is an auto-named `instance` (or a member whose
name-prefix is such an instance) whose source range sits inside an
`inductive`/`structure`/`class` in the same module — i.e. inside that type's
`deriving` clause. Hand-written top-level instances, structure projections, and
proof-fields are excluded.

These names are marked `isLeanGenerated` (see `runAnalysisViaLakeEnv`), **not
dropped**: the atoms stay in the dependency graph so transitive-verification
contamination still flows through them, while `viewify` filters them from the
web UI. Dropping them would be unsound — a surviving theorem depending on such an
instance would lose the contamination path through it and could be falsely
upgraded to `transitively-verified`. -/
def derivedInstanceClusterNames (decls : Array DeclInfo) : Std.HashSet Name := Id.run do
  -- Pre-index type-definition source ranges by module so each `insideTypeDef`
  -- check only scans ranges from the same module, not every type in the project.
  let mut typeRangesByModule : Std.HashMap Name (Array CodeTextInfo) := {}
  for d in decls do
    if d.kind == .inductive || d.kind == .structure || d.kind == .class then
      if let some r := d.sourceInfo then
        typeRangesByModule := typeRangesByModule.insert d.moduleName
          ((typeRangesByModule.getD d.moduleName #[]).push r)
  let insideTypeDef : DeclInfo → Bool := fun d =>
    match d.sourceInfo with
    | none => false
    | some r => (typeRangesByModule.getD d.moduleName #[]).any fun tr => coversRange tr r
  -- Auto-named instances synthesized inside a type definition = deriving output.
  let mut derived : Std.HashSet Name := {}
  for d in decls do
    if d.kind == .instance && insideTypeDef d then
      derived := derived.insert d.name
  -- Backing members of a derived instance (e.g. `instReprPoint.repr`).
  let mut result := derived
  for d in decls do
    if insideTypeDef d && derived.contains d.name.getPrefix then
      result := result.insert d.name
  return result

/-- Names of attribute-macro-generated companion theorems.

Some verification-framework attributes elaborate a tagged theorem into an
extra machine-generated theorem alongside it. The known case is Aeneas's
`@[step]`: for `theorem X`, it adds an mvcgen-shaped wrapper `X.mvcgen_spec`
whose declaration range is registered from the *tagging syntax* — the
inline `@[step]` line, or the `attribute [step] …` command, which can lie
outside `X`'s own range or even tag an external theorem. Via the source-scan
attribute fallback the companion also shows the parent's attributes. Left
untreated, it lands in every dependency's `specs` list next to the real spec
and defeats primary-spec detection (two tagged candidates where the signals
require exactly one).

A theorem named `<parent>.mvcgen_spec` qualifies unless `parent` is known to
be something other than a theorem. The parent's kind is resolved from the
emitted declarations first, then from `externalParentKind` (backed by the
full environment at the call site), so module filtering or an external
parent cannot misclassify. In particular:
- `parent` is a theorem (project or external) → companion (a theorem parent
  is the real spec: project theorems are collected into `specs` themselves);
- `parent` is unresolvable → companion (the name shape is Aeneas generator
  convention);
- `parent` is an **axiom** (project or external) → NOT a companion for our
  purposes: axioms are never collected into `specs` lists, so the wrapper is
  the specified def's only spec-shaped edge — the axiom's proxy. Excluding
  it would orphan every axiom-specified def.

The name shape is the whole signal; two corroborations considered and
rejected: (a) source ranges — the `attribute [step]` command form places the
companion's range outside the parent's, so containment checks reject exactly
the declarations this detection targets; (b) a dependency edge to the parent
— the wrapper references its parent only in the *proof term*. That edge is
observable here (a `DeclInfo`'s `termDependencies` holds raw, unfiltered
names), but requiring it would couple this detection to the generator's proof
shape — the wrapper happens to apply its parent today, and nothing pins that
across Aeneas versions — so the name shape stays the sole signal.
A hand-written theorem that happens to use the name shape is therefore flagged
(accepted false positive: the suffix is Aeneas generator convention, hiding
is mild, and an explicit `@[primary_spec]` tag restores it as primary
spec).

Companions are marked `isAeneasGenerated` + hidden — they exist only because
of Aeneas's attribute machinery, unlike `deriving` clusters and projections,
which are core-Lean output and carry `isLeanGenerated`. Either way they are
**not dropped**: they stay in the dependency graph so transitive-verification
contamination still flows through them. `computeSpecs` excludes generated
theorems (both flags) from spec bookkeeping unless explicitly tagged
`@[primary_spec]`. -/
def generatedCompanionTheoremNames (decls : Array DeclInfo)
    (externalParentKind : Name → Option DeclKind := fun _ => none) :
    Std.HashSet Name := Id.run do
  let mut kindByName : Std.HashMap Name DeclKind := {}
  for d in decls do
    kindByName := kindByName.insert d.name d.kind
  let mut result : Std.HashSet Name := {}
  for d in decls do
    -- The name shape is `Trust.isCompanionName`, shared with the trust rules so
    -- the two cannot disagree about what a companion is.
    if d.kind == .theorem && isCompanionName d.name then
      let parent := d.name.getPrefix
      match kindByName.get? parent <|> externalParentKind parent with
      | some .theorem | none => result := result.insert d.name
      | some _ => pure ()
  return result

/-- Every constant of the project's modules — **P** in the spec's terms: no name,
    kind or declaration-range filtering. This is the root set of the kernel taint
    walk; `getProjectDeclsFrom` carves the emitted declarations out of it. Sorted by
    structural `Name.lt` for determinism; the P14 string order is applied downstream,
    by `getProjectDeclsFrom`. -/
def projectConstants (env : Environment) (pf : ProjectFilter) : Array (Name × ConstantInfo) := Id.run do
  -- Enumerate the project modules' own `constNames` instead of scanning the whole
  -- imported constant map (`env.constants.map₁`, Mathlib included: ~0.5–1.2 s per
  -- run for 11–15k project constants; this takes ~15 ms). Membership is still
  -- decided by the environment's attribution (`pf.contains`), and the body is the
  -- one the environment kept (`env.find?`), never a module's own copy, so merged
  -- names and `computeProjectTaint`'s cross-merge augmentation are unchanged.
  let mods := env.header.moduleData
  let mut seen : Std.HashSet Name := {}
  let mut consts : Array (Name × ConstantInfo) := #[]
  for i in [:mods.size] do
    if pf.moduleIdxs.contains i then
      for n in mods[i]!.constNames do
        if seen.contains n then continue
        seen := seen.insert n
        if pf.contains env n then
          if let some ci := env.find? n then consts := consts.push (n, ci)
  -- Structural `Name.lt`, not `toString`: sorting 11k names by their printed form
  -- costs about two seconds on dalek, and nothing downstream needs string order
  -- (`getProjectDeclsFrom` re-sorts the emitted subset the P14 way).
  return consts.qsort fun a b => Name.lt a.1 b.1

/-- Whether a project constant is a *source-visible declaration*: it has a
    declaration range of its own and is neither an internal auxiliary
    (`X._proof_N`, `match_N`, …) nor a constructor/recursor. These are exactly the
    constants `extract` emits as atoms (when selected), and — minus generated
    companions, see `Trust.isCompanionName` — the only ones a human can put an
    `@[…]` attribute on. -/
def isSourceVisible (env : Environment) (name : Name) (info : ConstantInfo) : Bool :=
  !isInternalName name &&
  (match info with | .ctorInfo _ => false | .recInfo _ => false | _ => true) &&
  (declRangeExt.find? env name).isSome

/-- The emitted declarations among `consts` (a slice of P): source-visible
    constants whose module is selected by `selFilter`. Sorted by name (P14). -/
def getProjectDeclsFrom (env : Environment) (consts : Array (Name × ConstantInfo))
    (selFilter : ProjectFilter) : Array DeclInfo := Id.run do
  let modNames := env.allImportedModuleNames
  let mut decls : Array DeclInfo := #[]
  for (name, info) in consts do
    if !selFilter.contains env name then
      continue
    if !isSourceVisible env name info then
      continue
    decls := decls.push (analyzeDecl env modNames name info)
  decls.qsort fun a b => a.name.toString < b.name.toString

/-- The lexical state `stripLine` carries from one source line to the next: outside
    any literal, inside a block comment nested `depth` deep (docstrings included),
    inside a string literal, inside a raw string literal `r#"…"#` opened with that
    many hashes, or inside an interpolated string (`s!"…"`, `m!"…"`, `f!"…"`): its
    text (`interpString`), the code of a `{…}` interpolation `depth` braces deep
    (`interpCode`), or a plain string literal inside that code (`interpInnerString`),
    which returns to the interpolation when it closes. Block comments and every string
    form span lines in Lean, so a scan that starts mid-file in `.code` misreads
    whatever is open there — which is why `stripLines` always starts at line 0 and
    the result is cached per file (`SourceFile`). -/
inductive LexState where
  | code
  | comment (depth : Nat)
  | string
  | rawString (hashes : Nat)
  | interpString
  | interpCode (depth : Nat)
  | interpInnerString (depth : Nat)
  deriving BEq, Repr, Inhabited

/-- Whether `cs[i]` starts a token: it is the first character, or the previous one
    cannot continue an identifier (`x'` is one identifier, `'x'` is a char literal;
    `bar"` is not a raw string opener, `r"…"` is). -/
private def atTokenStart (cs : Array Char) (i : Nat) : Bool :=
  i == 0 || !(Lean.isIdRest cs[i - 1]!)

/-- Number of consecutive `#` from `cs[i]`. -/
private def countHashes (cs : Array Char) (i : Nat) : Nat := Id.run do
  let mut n := 0
  while cs[i + n]? == some '#' do n := n + 1
  return n

/-- The index just past a char literal starting at `cs[i] = '\''` — `'"'`, `'\n'`,
    `'\''`, `'\u{2200}'` — or `none` when what follows the quote is not one. -/
private def charLiteralEnd? (cs : Array Char) (i : Nat) : Option Nat := Id.run do
  if cs[i + 1]? == some '\\' then
    let mut j := i + 3
    while j < cs.size && cs[j]! != '\'' do j := j + 1
    return some (j + 1)
  else if cs[i + 2]? == some '\'' then
    return some (i + 3)
  else return none

/-- Whether the `"` at `cs[i]` opens an interpolated string: it is preceded by `!` and
    an identifier character (`s!"`, `m!"`, `f!"`, `throwError m!"`). -/
private def opensInterpolation (cs : Array Char) (i : Nat) : Bool :=
  i ≥ 2 && cs[i - 1]! == '!' && Lean.isIdRest cs[i - 2]!

/-- The code text of one source line: line comments, nested block comments, docstrings
    included, string literals, raw string literals, interpolated strings with their
    `{…}` code, char literals and `«…»` identifiers removed. `st` is the state at the
    start of the line; the state at its end is returned. Inside an interpolation, braces
    are counted and a nested plain string literal is skipped, so `s!"{(f "x")} {"@[…]"}"`
    is one literal rather than a string that closes at the inner `"` and leaks the inner
    literal's content as code. A nested *interpolated* string inside an interpolation is
    lexed as a plain one: recognising it would let an inner `"` mis-pair. That only
    affects the informative `attributes` array; trust reads the tag set (`TagSet`). A
    guillemet identifier's *content* is dropped because it may spell `@[…]`. -/
def stripLine (line : String) (st : LexState) : String × LexState := Id.run do
  let cs := line.toList.toArray
  let mut out : String := ""
  let mut st := st
  let mut i := 0
  while i < cs.size do
    let c := cs[i]!
    let next := cs[i + 1]?
    match st with
    | .comment depth =>
      if c == '/' && next == some '-' then
        st := .comment (depth + 1)
        i := i + 2
      else if c == '-' && next == some '/' then
        st := if depth ≤ 1 then .code else .comment (depth - 1)
        i := i + 2
      else
        i := i + 1
    | .string =>
      if c == '\\' then
        i := i + 2
      else
        if c == '"' then st := .code
        i := i + 1
    | .rawString hashes =>
      if c == '"' && countHashes cs (i + 1) ≥ hashes then
        st := .code
        i := i + 1 + hashes
      else
        i := i + 1
    | .interpString =>
      if c == '\\' then
        i := i + 2
      else
        if c == '"' then st := .code
        else if c == '{' then st := .interpCode 1
        i := i + 1
    | .interpCode depth =>
      if c == '{' then
        st := .interpCode (depth + 1)
        i := i + 1
      else if c == '}' then
        st := if depth ≤ 1 then .interpString else .interpCode (depth - 1)
        i := i + 1
      else if c == '"' then
        st := .interpInnerString depth
        i := i + 1
      else if c == '\'' && atTokenStart cs i then
        i := (charLiteralEnd? cs i).getD (i + 1)
      else
        i := i + 1
    | .interpInnerString depth =>
      if c == '\\' then
        i := i + 2
      else
        if c == '"' then st := .interpCode depth
        i := i + 1
    | .code =>
      if c == '-' && next == some '-' then
        break
      else if c == '/' && next == some '-' then
        st := .comment 1
        i := i + 2
      else if c == '"' then
        st := if opensInterpolation cs i then .interpString else .string
        i := i + 1
      else if c == 'r' && atTokenStart cs i && cs[i + 1 + countHashes cs (i + 1)]? == some '"' then
        let hashes := countHashes cs (i + 1)
        st := .rawString hashes
        i := i + 2 + hashes
      else if c == '\'' && atTokenStart cs i then
        -- A char literal. Anything else spelled with a leading quote is left as code.
        match charLiteralEnd? cs i with
        | some j => i := j
        | none =>
          out := out.push c
          i := i + 1
      else if c == '«' then
        let mut j := i + 1
        while j < cs.size && cs[j]! != '»' do j := j + 1
        i := j + 1
      else
        out := out.push c
        i := i + 1
  return (out, st)

/-- The code text of every line of a file, lexed once from the top so the comment and
    string state is right at every line. -/
def stripLines (lines : Array String) : Array String := Id.run do
  let mut out : Array String := Array.mkEmpty lines.size
  let mut st : LexState := .code
  for l in lines do
    let (code, st') := stripLine l st
    out := out.push code
    st := st'
  return out

/-- A cached source file: its lines, and their code text (`stripLines`). -/
structure SourceFile where
  lines : Array String
  code : Array String

def SourceFile.ofLines (lines : Array String) : SourceFile :=
  { lines, code := stripLines lines }

/-- File content cache to avoid re-reading (and re-lexing) the same file for every
    declaration. -/
abbrev FileCache := IO.Ref (Std.HashMap String SourceFile)

/-- Read a source file, using the cache. -/
def readSourceFile (cache : FileCache) (path : String) : IO SourceFile := do
  let map ← cache.get
  if let some f := map[path]? then
    return f
  let content ← IO.FS.readFile ⟨path⟩
  let f := SourceFile.ofLines (content.splitOn "\n" |>.toArray)
  cache.modify fun m => m.insert path f
  return f

/-- Parse attribute names out of a single `@[...]` block's inner content.
    E.g. `"progress, externally_verified"` → `#["progress", "externally_verified"]`. -/
private def parseAttrBlock (inside : String) : Array String := Id.run do
  let mut result : Array String := #[]
  for part in inside.splitOn "," do
    let trimmed := part.trimAscii.toString
    let attrName := (trimmed.splitOn " ").head!.trimAscii.toString
    if !attrName.isEmpty then
      result := result.push attrName
  return result

/-- Extract all `@[...]` blocks from a single line and return attribute names. -/
private def extractAttrsFromLine (line : String) : Array String := Id.run do
  let mut result : Array String := #[]
  -- Split on "@[" to find each block
  let parts := line.splitOn "@["
  -- First element is text before any @[, skip it
  for i in [1:parts.length] do
    let segment := parts[i]!
    -- Find the closing "]"
    let bracketParts := segment.splitOn "]"
    if bracketParts.length >= 1 then
      let inside := bracketParts[0]!
      for attr in parseAttrBlock inside do
        if !result.contains attr then
          result := result.push attr
  return result

/-- `code` with every `@[…]` block removed (an unclosed block runs to the end). -/
def removeAttrBlocks (code : String) : String := Id.run do
  let parts := code.splitOn "@["
  let mut out := parts.headD ""
  for p in parts.tail do
    match p.splitOn "]" with
    | _ :: rest => out := out ++ "]".intercalate rest
    | [] => pure ()
  return out

/-- Tokens that mark the head line of a declaration once comments, strings and
    `@[…]` blocks are gone. `:` covers `theorem x : …`, `instance : …` and `:=`;
    `|` an inductive's first constructor; the keywords catch heads with neither. -/
private def declHeadKeywords : Array String :=
  #["theorem", "lemma", "def", "abbrev", "instance", "axiom", "opaque", "structure",
    "inductive", "class", "example", "where"]

/-- Whether a line of code text (see `stripLine`) is a declaration head: outside its
    `@[…]` blocks it contains `:`, `|` or a declaration keyword. -/
def isDeclHeadLine (code : String) : Bool :=
  let rest := removeAttrBlocks code
  rest.any (fun c => c == ':' || c == '|') ||
    (rest.split Char.isWhitespace).any fun tok => declHeadKeywords.contains tok.toString

/-- What the header scan reads for one declaration: the attribute names, and the code
    text of the head lines — from the range's start through the head line
    (`isDeclHeadLine`), `@[…]` blocks removed. The head text is what `headerNamesDecl`
    tests; it feeds only the tag audit (`Taint.tagAudit`), never trust. -/
structure HeaderScan where
  attributes : Array String := #[]
  headCode : String := ""
  deriving Repr, BEq, Inhabited

/-- The header of a declaration whose source range covers lines `[startLine, endLine]`
    (0-based) of a file's **code text**. `lineAt` is the whole file lexed from the top,
    so a block comment, docstring or string literal that opened above the range is
    already gone. Only the declaration **header** is read: the scan stops after the
    head line, so an annotation in the body is never attributed to the declaration.
    Nothing before the range is read either: a declaration's range starts at its first
    modifier, docstring or `@[…]`, and a look-back would read a pure attribute line out
    of the previous declaration's body, since a syntax quotation ending in `)` is
    neither a head line nor a pure attribute line.

    The scan is by **line**, deliberately: a constant that shares a declaration's
    range — a `.mvcgen_spec` companion whose range starts at the `step` token of
    `@[step]`, an `@[ext]`-generated lemma, a `deriving` instance — is meant to show
    the declaration's attributes, and a column-based start would take that away. The
    companion of a `@[step]` axiom is that axiom's spec proxy for `primary-spec`. The
    price is that a second command on the same line as a tagged one shows the first's
    tag; that is cosmetic, since trust reads the tag set, and the tag audit
    (`Taint.tagAudit`) reports it. -/
def scanHeader (lineAt : Nat → Option String) (startLine endLine : Nat) : HeaderScan := Id.run do
  let mut attrs : Array String := #[]
  let mut head : String := ""
  for i in [startLine:endLine + 1] do
    let some line := lineAt i | break
    for attr in extractAttrsFromLine line do
      if !attrs.contains attr then attrs := attrs.push attr
    head := head ++ removeAttrBlocks line ++ " "
    if isDeclHeadLine line then break
  return { attributes := attrs, headCode := head }

/-- `scanHeader` over an array of code lines (tests). -/
def scanHeaderLines (code : Array String) (startLine endLine : Nat) : HeaderScan :=
  scanHeader (code[·]?) startLine endLine

/-- `scanHeader` over raw source lines: lexes the whole file first. -/
def attributesFromLines (lines : Array String) (startLine endLine : Nat) : Array String :=
  (scanHeaderLines (stripLines lines) startLine endLine).attributes

/-- Whether the head text of a declaration's header names the declaration: some
    identifier token equals the declaration's user-facing name or a dotted suffix of
    it (`theorem foo.bar` inside `namespace N` declares `N.foo.bar`; a `_root_.`
    prefix on the token is dropped first). An anonymous `instance : …` is named by
    the keyword instead, since its `inst…` name never appears in the source. This is
    what the source scan used to decide rule-2 trust with; it is kept for the tag
    audit only, because the suffix rule is wrong for generated helpers — Lean's
    `instInhabitedBox.default` shares the range of a one-line
    `@[externally_verified] structure Box where default : … deriving Inhabited`, ends
    in the field's name, and is neither a projection nor internal. -/
def headerNamesDecl (headCode : String) (name : Name) (isInstance : Bool) : Bool :=
  let user := (privateToUserName name).toString
  let tokens := headCode.split fun c => !(Lean.isIdRest c || c == '.')
  tokens.any fun tok =>
    let t := tok.toString
    let t := if t.startsWith "_root_." then (t.drop "_root_.".length).toString else t
    !t.isEmpty && (t == user || user.endsWith ("." ++ t) || (isInstance && t == "instance"))

/-- Scan the header of a declaration from its source file; see `scanHeader` for what
    is and is not read. `startLine`/`endLine` are the declaration range's **1-based**
    lines (`Lean.Position.line`, as in `CodeTextInfo`); they are converted to 0-based
    indices here. -/
def scanDeclHeader (cache : FileCache) (projectPath : System.FilePath)
    (codePath : String) (startLine endLine : Nat) : IO HeaderScan := do
  if codePath.isEmpty then return {}
  let file ← readSourceFile cache (projectPath / codePath).toString
  return scanHeader (file.code[·]?) (startLine - 1) (endLine - 1)

/-- `scanDeclHeader`'s attribute names alone. -/
def extractAttributesFromSource (cache : FileCache) (projectPath : System.FilePath)
    (codePath : String) (startLine endLine : Nat) : IO (Array String) :=
  (·.attributes) <$> scanDeclHeader cache projectPath codePath startLine endLine

/-- Strip leading "./" from a path string -/
def stripLeadingDotSlash (path : String) : String :=
  -- Replace multiple ./ patterns at the start
  let path := path.replace "././././" ""
  let path := path.replace "././" ""
  if path.startsWith "./" then (path.drop 2).toString else path

-- ============================================================
-- Auxiliary-dependency folding (issue #99)
--
-- Lean abstracts non-atomic embedded proofs and match arms into auxiliary
-- constants (`X._proof_N`, `X.match_N`, tactic-generated helpers). probe-lean
-- filters those out of its output (`isInternalName`), which used to lose every
-- edge underneath them: `host → aux → lemma` left no trace of `lemma`.
--
-- The fold is a strictly **additive** second pass. Governing invariant, whose
-- authoritative statement is `docs/SCHEMA.md` ("Auxiliary-dependency folding"),
-- quoted here:
--
--   It only ever *adds* names to `term-dependencies`. It never adds to
--   `type-dependencies`, never removes an entry from any of the four dependency
--   arrays, never adds to the `*-external` arrays, and never changes the atom
--   set.
--
-- `partitionDeps` keeps its behaviour byte-for-byte; the fold runs after it and
-- appends. Consequently edges to emitted project axioms/inductives/structures
-- and direct external anchors cannot be lost — their routing is never consulted.
-- ============================================================

/-- How the auxiliary-fold pass treats one dependency occurrence. -/
inductive DepClass where
  /-- A fold *target*: a project constant that survives the name filter and has
      a declaration range. Collected, never traversed through, so the fold does
      not flatten a host's graph past its real dependencies.

      That is every atom **plus named inductive constructors**: `isSourceVisible`
      additionally skips `.ctorInfo`/`.recInfo`, which this classifier does not
      mirror, so a project `Color.red` is a target while never being emitted as
      an atom of its own. Benign, and identical to how a *direct* edge to such a
      constructor already behaves: `partitionMissingDeps` treats a constructor
      whose parent type is extracted as benign. But "targets are exactly the
      atoms" is false, and `docs/auxiliary-folding.md` says so too. -/
  | emitted
  /-- Not emitted as an atom, value-bearing, not a structural member: traversed
      through, contributing whatever it reaches. -/
  | foldable
  /-- Neither a target nor traversable: constants outside the project filter
      *that survive the name filter*, structural members (`.mk`, `.injEq`,
      `.casesOn`, …), and non-value-bearing constants with no declaration range
      (axioms, inductives, constructors, recursors, `Quot`).

      Two boundaries worth stating, because neither is what the short form
      suggests. A *project* axiom or inductive with a range is `.emitted`, not
      `.ignored`. And "outside the project filter" is not sufficient on its own:
      an external constant the name filter drops (a Mathlib or core `_proof_N` /
      `match_N`) is value-bearing and `.foldable`, so it is traversed — only the
      *targets* collected are project-internal. That is deliberate. Under a
      module-prefix filter a non-project module can sit between two filtered
      modules, and an edge through its auxiliary is then genuinely recoverable.

      "Not foldable" is different from "not an edge" — but it is not "edge
      preserved" either, and which applies is decided by the name filter rather
      than by anything here. A direct reference that survives `isInternalName`
      stays in its project or `*-external` bucket as always; one the name filter
      catches (every structural-member suffix, the recursor suffixes included;
      a nested-inductive `Foo.rec_1` matches none) is dropped from
      all four arrays by `partitionDeps`, also as always. Constructors split on
      that same rule, not as a class: `Color.red` is kept, `Foo.mk` is not. -/
  | ignored
  /-- `env.find?` failed. Not silently dropped: reported once per extraction. -/
  | unresolved
  deriving DecidableEq, Repr, Inhabited

/-- Whether `name` is a structural member of a type rather than a term/proof
abstraction. Tested as a **string** suffix, the convention `isInternalName`
uses: `autoGeneratedSuffixes` holds multi-component entries like `.mk.injEq`, so
a last-component test is the wrong primitive.

Structural members are deliberately *not* folded through — mapping them to their
parent atom is a separate concern (they are members of an emitted type, not
hidden proof terms). -/
def isStructuralMemberName (name : Name) : Bool :=
  let str := (Lean.privateToUserName name).toString
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

/-- Classify one dependency occurrence for the fold.

`env.find?` is consulted **first**, before any name or kind test, so a missing
`Missing.mk` is reported as unresolved rather than silently dropped by suffix.

`isProjectMember` is passed as a predicate rather than a `ProjectFilter` so the
classifier is exercisable against a real `Environment` in tests (locally
elaborated constants have no module index) and so "restricted-library
extraction" — a narrower project set — is expressible. In production it is
`projFilter.contains env`. -/
def classifyFoldCandidate (env : Environment) (isProjectMember : Name → Bool)
    (n : Name) : DepClass :=
  match env.find? n with
  | none => .unresolved
  | some info =>
    let isProj := isProjectMember n
    -- Not emitted as an atom: dropped by name (`isInternalName`), or a project
    -- member the environment walk skips for having no declaration range.
    let notEmitted := isInternalName n || (isProj && (declRangeExt.find? env n).isNone)
    if notEmitted then
      if isStructuralMemberName n then .ignored
      else
        -- Exhaustive over `ConstantInfo` via `valueOf` (no wildcard), so a
        -- future value-bearing constructor fails compilation rather than being
        -- silently skipped.
        match valueOf info with
        | some _ => .foldable
        | none   => .ignored
    else if isProj then .emitted
    else .ignored

/-- Cross-root state for the auxiliary-fold traversal.

`cache` holds only **complete** closures (rule 4 in `foldedDeps`), keyed to one
immutable `Environment` and one classification policy. Extraction is sequential
and builds one state per run — that is the cache's stated invariant, not a
silent assumption. Cached closures are project-filtered but **not**
host-filtered: self-edge suppression happens at the host merge, so a closure
shared by two hosts stays correct for both.

-/
structure FoldState where
  /-- Complete, project-filtered, deduplicated closures, by node. -/
  cache : Std.HashMap Name (Array Name) := {}
  /-- Per-root visited set. Reset by `foldedDepsFrom` for each closure query. -/
  visited : Std.HashSet Name := {}
  /-- Names `env.find?` could not resolve, deduplicated for one report. -/
  unresolved : Std.HashSet Name := {}
  /-- Node expansions (performance gate). -/
  expansions : Nat := 0
  /-- Edges scanned (performance gate). -/
  edgesScanned : Nat := 0
  /-- Revisits suppressed because the node was already visited in this root
      query and had no cached complete closure — i.e. how often rule 2 fired.
      Not a count of incomplete expansions: one expansion can suppress several
      revisits, and an expansion that is incomplete only because a descendant
      was does not appear here. Nor is every suppression an active back-edge; the
      skipped node may be one that already completed without becoming cacheable.
      Reported, because a run where this stays 0 has not exercised the cycle
      rules at all. -/
  nonCacheable : Nat := 0
  /-- Dependency entries the fold added (the recovered edges). -/
  addedEdges : Nat := 0

/-- A traversal policy: the out-edges to follow and how to classify what they
reach. Bundling the two means a caller cannot supply a `children` from one policy
and a `classify` from another.

It does **not** tie the policy to a `FoldState`: a cached closure is only valid
for the walk that built it, but that is an invariant the caller upholds, not one
the types enforce — `foldedDepsFrom` takes the walk and the state independently.
The single production caller establishes it by building one state per extraction
run alongside one walk (`ProbeLean/Atomize.lean`). -/
structure FoldWalk where
  children : Name → Array Name
  classify : Name → DepClass

/-- The production traversal policy: full reachability (`constChildren`, i.e. a
node's type *and* value constants) under the project filter. -/
def FoldWalk.ofEnv (env : Environment) (isProjectMember : Name → Bool) : FoldWalk :=
  { children := constChildren env
    classify := classifyFoldCandidate env isProjectMember }

/-- Deduplicate and sort names by their string form, the project's determinism
convention (P14). -/
def sortDedupNames (arr : Array Name) : Array Name :=
  let s : Std.HashSet Name := arr.foldl (init := {}) fun s n => s.insert n
  s.toArray.qsort fun a b => a.toString < b.toString

/-- Project-emitted constants reachable from `n` through foldable nodes only.

Returns `(targets, cacheable)`. `cacheable := false` when the result was
computed across a skipped back-edge and may therefore be incomplete. A *root*
result is always complete (DFS collects every discovered node's emitted children
and propagates them up the discovery tree); only intermediate frames can be
partial, which is exactly what the flag records.

Four rules:

1. **Per-root visited set** bounds one traversal to a bounded number of node
   expansions. Without it, a cyclic region where every branch hits a back-edge
   and nothing is cacheable can enumerate exponentially many paths through a
   linear-size graph. Visitation resets for each independent closure query
   (`foldedDepsFrom`) — sharing it across queries would let one query's
   suppressions silently truncate the next.
2. **Every visited-set suppression returns non-cacheable**, after a complete
   cached result has been checked for, and whether the skipped node is still
   active or has already completed without being cacheable. Otherwise a node
   that completed incompletely could be re-read as an authoritative empty
   result by a later sibling.
3. **Cacheability propagates transitively**: an ancestor that consumed an
   incomplete result is itself incomplete and must stay out of the cache.
   Suppressing caching only in the detecting frame is not enough.
4. **The cache stores only `cacheable` results**, project-filtered and
   deduplicated during construction.

Generic over `children`/`classify` so the traversal is unit-testable without an
`Environment`.

On reachability: a cycle in `constChildren`'s raw graph is not enough to exercise
any of this, because every node on it must also classify `.foldable`. `Foo →
Foo.mk → Foo` — the obvious candidate — cannot be entered at all: `Foo.mk` ends
with a `autoGeneratedSuffixes` entry, so `isStructuralMemberName` sends it to
`.ignored`. A self-recursive internal-named definition does reach it, e.g.

    unsafe def _foldCycle (arg : Nat) : Nat := _foldCycle arg

which is `.foldable` and appears among its own children. No *naturally occurring*
instance has been observed yet: `FoldState.nonCacheable` was 0 across
curve25519-dalek-lean-verify, which is why `extract` reports that counter. So the
rules below are a termination guarantee for a shape the traversal admits, not a
response to a measured one. -/
private partial def foldedDepsCore (w : FoldWalk) (n : Name) :
    StateM FoldState (Array Name × Bool) := do
  if let some hit := (← get).cache[n]? then
    return (hit, true)
  if (← get).visited.contains n then
    modify fun s => { s with nonCacheable := s.nonCacheable + 1 }
    return (#[], false)
  let kids := w.children n
  modify fun s => { s with
    visited := s.visited.insert n
    expansions := s.expansions + 1
    edgesScanned := s.edgesScanned + kids.size }
  let mut acc : Array Name := #[]
  let mut cacheable := true
  for ch in kids do
    match w.classify ch with
    | .emitted => acc := acc.push ch
    | .foldable =>
      let (sub, subCacheable) ← foldedDepsCore w ch
      acc := acc ++ sub
      unless subCacheable do cacheable := false
    | .unresolved => modify fun s => { s with unresolved := s.unresolved.insert ch }
    | .ignored => pure ()
  let targets := sortDedupNames acc
  if cacheable then
    modify fun s => { s with cache := s.cache.insert n targets }
  return (targets, cacheable)

/-- One independent closure query: `foldedDepsCore` with a fresh per-root visited
set (rule 1). This is the **only** entry point — the recursive worker is private
because calling it on an already-used state silently truncates any
visited-but-uncached node, and that is exactly the cyclic case.

A root's result is always complete, so the cacheability flag (internal
bookkeeping) is not returned. -/
def foldedDepsFrom (w : FoldWalk) (n : Name) : StateM FoldState (Array Name) := do
  modify fun s => { s with visited := {} }
  let (targets, _) ← foldedDepsCore w n
  return targets

/-- Union of the closures of every foldable occurrence in `raw`. Unresolved
occurrences are recorded rather than dropped. -/
def foldOccurrences (w : FoldWalk) (raw : Array Name) : StateM FoldState (Array Name) := do
  let mut acc : Array Name := #[]
  for d in raw do
    match w.classify d with
    | .foldable => acc := acc ++ (← foldedDepsFrom w d)
    | .unresolved => modify fun s => { s with unresolved := s.unresolved.insert d }
    | _ => pure ()
  return acc

/-- Additive fold of one dependency list.

`raw` is the declaration's unfiltered dependency occurrences; `proj` is what
`partitionDeps` already produced for that list. Every foldable occurrence — the
internal names `partitionDeps` dropped, plus project members it kept that are
not emitted as atoms — is traversed, and the targets are **appended** to `proj`.
Nothing is removed or rerouted, so a dangling direct edge to a non-emitted
project name is kept *as well as* folded and the missing-dependency warning
still fires.

`host` is dropped from the folded targets (`H → aux → H` is not a self-loop the
graph needs); suppression is per-host and never enters the cache. -/
def mergeFolded (host : Name) (proj extra : Array Name) :
    StateM FoldState (Array Name) := do
  if extra.isEmpty then return proj
  let merged := sortDedupNames (proj ++ extra.filter (· != host))
  modify fun s => { s with addedEdges := s.addedEdges + (merged.size - proj.size) }
  return merged

/-- `foldOccurrences` followed by `mergeFolded`: the whole additive fold of one
dependency list under a single scope. -/
def foldDepList (w : FoldWalk) (host : Name) (raw : Array Name) (proj : Array Name) :
    StateM FoldState (Array Name) := do
  mergeFolded host proj (← foldOccurrences w raw)

/-- The fold state, shared across one extraction run. -/
abbrev AuxDepCache := IO.Ref FoldState

/-- Fold one declaration's type and term dependency lists, and recompute the
`dependencies` union from the folded results.

`dependencies` is documented as the deduplicated union of `type-dependencies`
and `term-dependencies`, and is now derived here from the folded arrays. It used
to be computed independently, by filtering `info.dependencies` with its own copy
of the project-membership test; that produced the same set only because the copy
and `partitionDeps` classified identically. Deriving the union from the arrays it
is documented to be the union of removes that coupling, and
`tools/audit/compare-extract.py` asserts the identity on real output so a future
divergence fails loudly instead of dropping entries. -/
def foldAtomDeps (env : Environment) (isProjectMember : Name → Bool)
    (auxCache : AuxDepCache) (info : DeclInfo)
    (projTypeDeps projTermDeps : Array Name) :
    IO (Array Name × Array Name × Array Name) := do
  let walk := FoldWalk.ofEnv env isProjectMember
  let act : StateM FoldState (Array Name × Array Name × Array Name) := do
    -- Recovered edges all land in `term-dependencies`, including those found
    -- under an auxiliary the *type* named. `type-dependencies` therefore stays
    -- exactly what `partitionDeps` produced — syntactically what the signature
    -- mentions — so the fold leaves *type-driven* spec selection untouched:
    -- `computeSpecs` walks that array to decide what a theorem specifies.
    --
    -- It is not a blanket "`specs` cannot change" guarantee. `specTargets`
    -- (`ProbeLean/Atomize.lean`) has one fallback that reads the union
    -- `dependencies`: a `@[primary_spec]`-tagged theorem whose statement names
    -- nothing specifiable. A folded *term* edge can add a second candidate
    -- there and detach the tag with `type-dependencies` byte-identical — see
    -- `testPrimarySpecFoldFallback` in `Tests/Main.lean`.
    --
    -- The alternative (route a type-position auxiliary's *type* reach into the
    -- type bucket, its *value* reach into the term bucket) was implemented and
    -- measured: it needs a third traversal per declaration under a second cache
    -- partition, and cost +54% extract wall-clock on a 2354-atom project against
    -- a +2 s budget, to move 4 edges. A folded edge is indirect by construction,
    -- so the bucket whose consumers tolerate indirection is the right home for
    -- all of them; `dependencies` (the union) carries them either way, which is
    -- what verification-status propagation reads.
    let fromType ← foldOccurrences walk info.typeDependencies
    let fromTerm ← foldOccurrences walk info.termDependencies
    let foldedTerm ← mergeFolded info.name projTermDeps (fromType ++ fromTerm)
    return (sortDedupNames (projTypeDeps ++ foldedTerm), projTypeDeps, foldedTerm)
  let st ← auxCache.get
  let (result, st) := act.run st
  auxCache.set st
  return result

/-- Per-module cache of `getModuleSourcePath` results (project-relative, `./`
    stripped, `""` when the source file is not found). One `pathExists` per module
    instead of one per declaration. -/
abbrev ModulePathCache := IO.Ref (Std.HashMap Name String)

/-- `getModuleSourcePath` through the cache. -/
def moduleSourcePathCached (cache : ModulePathCache) (env : Environment)
    (projectPath : System.FilePath) (modName : Name) : IO String := do
  if let some p := (← cache.get)[modName]? then
    return p
  let p := match ← getModuleSourcePath env projectPath modName with
    | some p => stripLeadingDotSlash p
    | none => ""
  cache.modify (·.insert modName p)
  return p

/-- A declaration's attributes, as `declAttributes` computes them. -/
structure DeclAttrs where
  /-- The emitted `attributes` array: the tag-set and handle tags plus every scanned
      `@[…]` name. -/
  attributes : Array String := #[]
  /-- The scanned header carries `externally_verified` (whether or not it names the
      declaration): a range-sharer *shows* its neighbour's tag this way. -/
  headerShowsTag : Bool := false
  /-- The scanned header carries `externally_verified` **and** its head line names the
      declaration (`headerNamesDecl`): what the source scan used to trust. Audit input
      only (`Taint.tagAudit`) — trust is decided by the tag set (`TagSet`). -/
  headerNamesTag : Bool := false
  deriving Repr, BEq, Inhabited

/-- The attributes of a declaration: `externally_verified` when `tagged` (the caller
    read the tag set from the environment, `TagSet.externallyVerifiedTagSet`, and
    probe-lean's own handle), `primary_spec` from probe-lean's handle, plus — when
    `scanSource` — every `@[…]` name scanned from the header of `range`. The scan is
    informative: it is the only source for attributes probe-lean does not register
    (`step`, `progress`, `simp`, …) and its two `header*` findings feed the tag audit.
    The **one** place attributes are computed: the atom's `attributes` array and the
    audit both read this. -/
def declAttributes (env : Environment) (projectPath : System.FilePath) (fileCache : FileCache)
    (pathCache : ModulePathCache) (name moduleName : Name) (range : Option CodeTextInfo)
    (scanSource : Bool) (isInstance : Bool := false) (tagged : Bool := false) : IO DeclAttrs := do
  let mut attrs : Array String := #[]
  let mut shows := false
  let mut names := false
  if primarySpecAttr.hasTag env name then
    attrs := attrs.push "primary_spec"
  if tagged then
    attrs := attrs.push "externally_verified"
  if scanSource then
    if let some r := range then
      let sourcePathStr ← moduleSourcePathCached pathCache env projectPath moduleName
      let header ← scanDeclHeader fileCache projectPath sourcePathStr r.linesStart r.linesEnd
      for sa in header.attributes do
        if !attrs.contains sa then
          attrs := attrs.push sa
      if header.attributes.contains "externally_verified" then
        shows := true
        names := headerNamesDecl header.headCode name isInstance
  return { attributes := attrs.qsort (· < ·), headerShowsTag := shows, headerNamesTag := names }

/-- Convert a DeclInfo to an Atom. `attrs` is the declaration's attribute list from
    `declAttributes`, computed once by the caller (`Taint.computeAttributes`) for every
    source-visible constant of P: the tag audit needs them for non-emitted constants
    too. -/
def declInfoToAtom (env : Environment) (projectPath : System.FilePath) (projFilter : ProjectFilter)
    (crate : String) (pathCache : ModulePathCache) (auxCache : AuxDepCache)
    (attrs : Array String) (info : DeclInfo) : IO Atom := do
  let sourcePathStr ← match info.sourceInfo with
    | some _ => moduleSourcePathCached pathCache env projectPath info.moduleName
    | none => pure ""

  -- External (non-project) deps: referenced but outside the project (Mathlib,
  -- core). Emitted alongside the project-filtered deps so a downstream
  -- classifier gets the direct edges to external anchors that
  -- `projTypeDeps`/`projTermDeps` drop (direct only: the fold never adds here,
  -- see `docs/auxiliary-folding.md`).
  --
  -- Partitioned in one pass per list rather than filtered once per output array:
  -- `isInternalName` scans the name and the module lookup hashes it, and with
  -- proof terms included these lists run to tens of thousands of entries per
  -- project. Input order is preserved, so both outputs stay name-sorted (P14).
  let partitionDeps (deps : Array Name) : Array Name × Array Name :=
    deps.foldl (init := (#[], #[])) fun (proj, ext) dep =>
      if isInternalName dep then (proj, ext)
      else if projFilter.contains env dep then (proj.push dep, ext)
      else (proj, ext.push dep)

  let (directProjTypeDeps, extTypeDeps) := partitionDeps info.typeDependencies
  let (directProjTermDeps, extTermDeps) := partitionDeps info.termDependencies

  -- Additive auxiliary fold (issue #99): recover the project edges hidden under
  -- non-emitted auxiliaries. `ext*` above are already final — the fold never
  -- touches them (see the `DepClass` invariant note).
  let (projDeps, projTypeDeps, projTermDeps) ←
    foldAtomDeps env (projFilter.contains env) auxCache info
      directProjTypeDeps directProjTermDeps

  let rustSource ← getDeclRustSource env info.name
  let isRelevant := if crate.isEmpty then true else isRelevantSource rustSource crate
  let isPrimarySpec := primarySpecAttr.hasTag env info.name

  return {
    name := probeRef info.name
    leanName := info.name
    displayName := info.displayName
    dependencies := projDeps.map probeRef
    typeDependencies := projTypeDeps.map probeRef
    termDependencies := projTermDeps.map probeRef
    typeDependenciesExternal := extTypeDeps.map probeRef
    termDependenciesExternal := extTermDeps.map probeRef
    codeModule := info.moduleName.toString
    codePath := sourcePathStr
    codeText := if sourcePathStr.isEmpty then none else info.sourceInfo
    kind := info.kind
    isRelevant := isRelevant
    isInPackage := true
    rustSource := rustSource
    attributes := attrs
    isPrimarySpec := isPrimarySpec
    codomainHead := info.codomainHead.map (·.toString)
    codomainIsProp := info.codomainIsProp
    codomainLastArgIsBool := info.codomainLastArgIsBool
  }

end ProbeLean
