import Lean
open Lean

/-- Where do internal auxiliaries sit — in a declaration's *type* or its *value*?
Folding type-position auxiliaries changes `typeDependencies`, which is what
`computeSpecs` walks, so it has a blast radius on `specs`/`primary-spec`. -/

def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",
  ".mk", ".elim", ".ctorIdx", ".toCtorIdx"
]

def containsSubstring (s sub : String) : Bool := (s.splitOn sub).length > 1

def isInternalName (name : Name) : Bool :=
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  | _             => none

def usedConsts (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants ++ (valueOf ci).elim #[] Expr.getUsedConstants

structure Ctx where
  env : Environment
  prefixes : Array Name

def Ctx.inTarget (c : Ctx) (n : Name) : Bool :=
  if isInternalName n then false
  else match c.env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match c.env.allImportedModuleNames[idx.toNat]? with
    | none => false
    | some m => c.prefixes.any fun p => m == p || m.toString.startsWith (p.toString ++ ".")

partial def auxClosure (c : Ctx) (n : Name) (acc : Std.HashSet Name) (seen : Std.HashSet Name)
    : Std.HashSet Name × Std.HashSet Name :=
  if seen.contains n then (acc, seen) else
  let seen := seen.insert n
  match c.env.find? n with
  | none => (acc, seen)
  | some ci =>
    (usedConsts ci).foldl (init := (acc, seen)) fun (acc, seen) d =>
      if isInternalName d then auxClosure c d acc seen else (acc.insert d, seen)

def isThm : ConstantInfo → Bool
  | .thmInfo _ => true
  | _ => false

def main (args : List String) : IO Unit := do
  initSearchPath (← findSysroot)
  let prefixes := (args.map fun s => s.toName).toArray
  let env ← importModules (prefixes.map fun p => ({ module := p } : Import)) {} (trustLevel := 1024)
  let c : Ctx := { env, prefixes }

  let mut atoms := 0
  let mut auxInType := 0        -- aux occurrences in type position
  let mut auxInValue := 0
  let mut declsAuxInType := 0   -- decls with >=1 aux in the type
  let mut typeHidesProj := 0    -- project edges hidden by type-position aux
  let mut typeHidesExt := 0
  let mut valueHidesProj := 0
  let mut valueHidesExt := 0
  let mut thmSpecsChange := 0   -- theorem atoms whose typeDeps gain a non-theorem project const
  let mut thmSpecsGained := 0

  -- which project atoms are non-theorems (spec targets)
  let mut nonThm : Std.HashSet Name := {}
  for (name, ci) in env.constants.map₁.toList do
    if c.inTarget name && (declRangeExt.find? env name).isSome && !isThm ci then
      nonThm := nonThm.insert name

  for (name, ci) in env.constants.map₁.toList do
    unless c.inTarget name do continue
    match ci with
    | .ctorInfo _ | .recInfo _ => continue
    | _ => pure ()
    unless (declRangeExt.find? env name).isSome do continue
    atoms := atoms + 1
    let tyConsts := ci.type.getUsedConstants
    let valConsts := (valueOf ci).elim #[] Expr.getUsedConstants
    let visibleTy := tyConsts.filter fun d => !isInternalName d
    let visibleAll := (tyConsts ++ valConsts).filter fun d => !isInternalName d
    let auxTy := tyConsts.filter isInternalName
    let auxVal := valConsts.filter isInternalName
    auxInType := auxInType + auxTy.size
    auxInValue := auxInValue + auxVal.size
    if !auxTy.isEmpty then declsAuxInType := declsAuxInType + 1

    let foldOf (auxes : Array Name) (visible : Array Name) : List Name × List Name := Id.run do
      let mut lost : Std.HashSet Name := {}
      let mut seen : Std.HashSet Name := {}
      for a in auxes do
        let (acc, s) := auxClosure c a lost seen
        lost := acc; seen := s
      let new := lost.toList.filter fun d => !visible.contains d && d != name
      return new.partition c.inTarget

    let (tp, te) := foldOf auxTy visibleTy
    typeHidesProj := typeHidesProj + tp.length
    typeHidesExt := typeHidesExt + te.length
    let (vp, ve) := foldOf auxVal visibleAll
    valueHidesProj := valueHidesProj + vp.length
    valueHidesExt := valueHidesExt + ve.length

    if isThm ci then
      let gained := tp.filter nonThm.contains
      if !gained.isEmpty then
        thmSpecsChange := thmSpecsChange + 1
        thmSpecsGained := thmSpecsGained + gained.length

  IO.println s!"atoms                                  : {atoms}"
  IO.println s!"aux occurrences in type / in value     : {auxInType} / {auxInValue}"
  IO.println s!"decls with >=1 aux in the type         : {declsAuxInType}"
  IO.println s!"project edges hidden: type / value     : {typeHidesProj} / {valueHidesProj}"
  IO.println s!"external edges hidden: type / value    : {typeHidesExt} / {valueHidesExt}"
  IO.println s!"theorems whose `specs` targets change  : {thmSpecsChange} (+{thmSpecsGained} spec edges)"
