import Lean
open Lean

def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",
  ".mk", ".elim", ".ctorIdx", ".toCtorIdx"
]

def containsSubstring (s sub : String) : Bool := (s.splitOn sub).length > 1

def isInternalName (name : Name) : Bool :=
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  | _             => none

def usedConsts (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants ++ (valueOf ci).elim #[] Expr.getUsedConstants

structure Ctx where
  env : Environment
  prefixes : Array Name

def Ctx.inTarget (c : Ctx) (n : Name) : Bool :=
  if isInternalName n then false
  else match c.env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match c.env.allImportedModuleNames[idx.toNat]? with
    | none => false
    | some m => c.prefixes.any fun p => m == p || m.toString.startsWith (p.toString ++ ".")

partial def auxClosure (c : Ctx) (n : Name) (acc : Std.HashSet Name) (seen : Std.HashSet Name)
    : Std.HashSet Name × Std.HashSet Name :=
  if seen.contains n then (acc, seen) else
  let seen := seen.insert n
  match c.env.find? n with
  | none => (acc, seen)
  | some ci =>
    (usedConsts ci).foldl (init := (acc, seen)) fun (acc, seen) d =>
      if isInternalName d then auxClosure c d acc seen else (acc.insert d, seen)

/-- Does this declaration's own type/value mention `sorryAx` directly? Stands in
for probe-lean's build-warning-based "unverified" root set. -/
def locallySorried (ci : ConstantInfo) : Bool :=
  (usedConsts ci).any fun d => d == ``sorryAx

def main (args : List String) : IO Unit := do
  let prefixes := (args.map fun s => s.toName).toArray
  initSearchPath (← findSysroot)
  let env ← importModules (prefixes.map fun p => ({ module := p } : Import)) {} (trustLevel := 1024)
  let c : Ctx := { env, prefixes }

  let mut atoms : Array Name := #[]
  let mut visibleDeps : Std.HashMap Name (Array Name) := {}   -- graph probe-lean emits
  let mut foldedDeps : Std.HashMap Name (Array Name) := {}    -- graph after folding aux
  let mut indeg : Std.HashMap Name Nat := {}
  let mut sorryRoots : Array Name := #[]

  for (name, ci) in env.constants.map₁.toList do
    unless c.inTarget name do continue
    match ci with
    | .ctorInfo _ | .recInfo _ => continue
    | _ => pure ()
    unless (declRangeExt.find? env name).isSome do continue
    atoms := atoms.push name
    if locallySorried ci then sorryRoots := sorryRoots.push name
    let direct := usedConsts ci
    let visible := (direct.filter fun d => !isInternalName d && c.inTarget d && d != name)
    visibleDeps := visibleDeps.insert name visible
    for d in visible do indeg := indeg.insert d ((indeg.getD d 0) + 1)
    let auxes := direct.filter isInternalName
    let mut lost : Std.HashSet Name := {}
    let mut seen : Std.HashSet Name := {}
    for a in auxes do
      let (acc, s) := auxClosure c a lost seen
      lost := acc; seen := s
    let extra := lost.toList.filter fun d => c.inTarget d && !visible.contains d && d != name
    foldedDeps := foldedDeps.insert name (visible ++ extra.toArray)

  -- forward taint: a decl is tainted if any dep is tainted (fixpoint)
  let taint (g : Std.HashMap Name (Array Name)) : Std.HashSet Name := Id.run do
    let mut t : Std.HashSet Name := sorryRoots.foldl (init := {}) (·.insert ·)
    let mut changed := true
    while changed do
      changed := false
      for a in atoms do
        unless t.contains a do
          if (g.getD a #[]).any t.contains then
            t := t.insert a; changed := true
    return t

  let tVisible := taint visibleDeps
  let tFolded := taint foldedDeps
  let missed := atoms.filter fun a => tFolded.contains a && !tVisible.contains a

  IO.println s!"atoms                        : {atoms.size}"
  IO.println s!"locally sorried (roots)      : {sorryRoots.size}"
  IO.println s!"tainted, emitted graph       : {tVisible.size}"
  IO.println s!"tainted, aux-folded graph    : {tFolded.size}"
  IO.println s!"MISSED taint (status wrong)  : {missed.size}"
  for m in missed.toList.take 25 do IO.println s!"    {m}"

  let rescued := atoms.filter fun a => indeg.getD a 0 == 0 &&
    atoms.any fun b => (foldedDeps.getD b #[]).contains a
  IO.println s!"in-degree 0 -> >0            : {rescued.size}"
  for r in rescued.toList.take 30 do IO.println s!"    {r}"
