/-
  Oracle for the shipped auxiliary fold (issue #99).

  Audit.lean–Audit5.lean measured the *problem* by folding every filtered class.
  This script re-derives what the **shipped** predicate should add, per atom and
  per bucket, and prints it as a stable TSV so it can be compared against a real
  `extract` artifact:

      <atom>\t(type|term)\t<target>

  It is deliberately an independent implementation of the same contract:

  - the classification is written out by hand here, not imported, so a bug in
    `ProbeLean.classifyFoldCandidate` cannot validate itself;
  - the traversal has **no cross-root cache** — one fresh visited set per closure
    query, which is precisely the machinery most likely to be wrong in the
    shipped version (`FoldState.cache`, and the cacheability flag that guards
    it). An oracle that shared the caching strategy would share its bugs.

  An oracle built from the same contract still cannot prove the contract right.
  Pair it with the hand-checked expectations in README.md and with the
  invariant gate in `compare-extract.py`.

  Run (from the target project, under the *target's* toolchain):

      cd <target>
      env -u LEAN_PATH bash -lc 'source ~/.elan/env; \
        lake env lean --run <probe-lean>/tools/audit/Audit6.lean <ModulePrefix>...' \
        > /tmp/oracle.tsv
-/
import Lean
open Lean

/-- Copied from `ProbeLean/Analysis.lean` so the oracle stays independent of the
code it checks. -/
def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",
  ".mk", ".elim", ".ctorIdx", ".toCtorIdx"
]

def containsSubstring (s sub : String) : Bool := (s.splitOn sub).length > 1

def isInternalName (name : Name) : Bool :=
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def isStructuralMemberName (name : Name) : Bool :=
  let str := (Lean.privateToUserName name).toString
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  | _             => none

/-- `constChildren`: type constants ++ value constants (++ constructors, for an
inductive — never reached, since inductives are not foldable). -/
def children (env : Environment) (c : Name) : Array Name :=
  match env.find? c with
  | some (.axiomInfo v)  => v.type.getUsedConstants
  | some (.defnInfo v)   => v.type.getUsedConstants ++ v.value.getUsedConstants
  | some (.thmInfo v)    => v.type.getUsedConstants ++ v.value.getUsedConstants
  | some (.opaqueInfo v) => v.type.getUsedConstants ++ v.value.getUsedConstants
  | some (.ctorInfo v)   => v.type.getUsedConstants
  | some (.recInfo v)    => v.type.getUsedConstants
  | some (.inductInfo v) => v.type.getUsedConstants ++ v.ctors.toArray
  | some (.quotInfo _)   => #[]
  | none                 => #[]

inductive Cls where | emitted | foldable | ignored | unresolved
  deriving DecidableEq

structure Ctx where
  env : Environment
  prefixes : Array Name

def Ctx.isProject (c : Ctx) (n : Name) : Bool :=
  match c.env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match c.env.allImportedModuleNames[idx.toNat]? with
    | none => false
    | some m => c.prefixes.any fun p => m == p || m.toString.startsWith (p.toString ++ ".")

def Ctx.classify (c : Ctx) (n : Name) : Cls :=
  match c.env.find? n with
  | none => .unresolved
  | some info =>
    let isProj := c.isProject n
    let notEmitted := isInternalName n || (isProj && (declRangeExt.find? c.env n).isNone)
    if notEmitted then
      if isStructuralMemberName n then .ignored
      else match valueOf info with
        | some _ => .foldable
        | none   => .ignored
    else if isProj then .emitted
    else .ignored

/-- Naive closure: fresh visited set per query, no cross-root memo. -/
partial def closure (c : Ctx) (n : Name) (acc : Std.HashSet Name)
    (seen : Std.HashSet Name) : Std.HashSet Name × Std.HashSet Name :=
  if seen.contains n then (acc, seen) else
  let seen := seen.insert n
  (children c.env n).foldl (init := (acc, seen)) fun (acc, seen) d =>
    match c.classify d with
    | .emitted  => (acc.insert d, seen)
    | .foldable => closure c d acc seen
    | _         => (acc, seen)

/-- Everything reachable through `raw`'s foldable occurrences. Unfiltered: the
per-bucket subtraction happens at the routing step, as `mergeFolded` does it. -/
def reachFor (c : Ctx) (raw : Array Name) : Std.HashSet Name := Id.run do
  let mut acc : Std.HashSet Name := {}
  for d in raw do
    if c.classify d == .foldable then
      -- One fresh visited set per occurrence, mirroring `foldedDepsFrom`.
      let (acc', _) := closure c d acc {}
      acc := acc'
  return acc

def sorted (s : Std.HashSet Name) : Array Name :=
  s.toArray.qsort fun a b => a.toString < b.toString

/-- Render a name the way the artifact does: `probeRef` strips the private
mangling (`_private.M.0.Bar.foo` → `Bar.foo`), so the oracle must too or every
private declaration reads as a mismatch. Classification and self-edge
suppression above work on the *raw* names, as in probe-lean. -/
def render (n : Name) : String := (Lean.privateToUserName n).toString

def main (args : List String) : IO Unit := do
  let prefixes := (args.map fun s => s.toName).toArray
  initSearchPath (← findSysroot)
  let env ← importModules (prefixes.map fun p => ({ module := p } : Import)) {}
    (trustLevel := 1024) (level := OLeanLevel.private)
  let c : Ctx := { env, prefixes }
  let mut rows : Array String := #[]
  for (name, ci) in env.constants.map₁.toList do
    unless c.isProject name && !isInternalName name do continue
    match ci with
    | .ctorInfo _ | .recInfo _ => continue
    | _ => pure ()
    unless (declRangeExt.find? env name).isSome do continue
    let typeRaw := ci.type.getUsedConstants
    let valRaw := (valueOf ci).elim #[] Expr.getUsedConstants
    -- Every recovered edge is a term edge: `type-dependencies` is left exactly
    -- as `partitionDeps` produced it, so the fold cannot perturb `specs`.
    let directTerm := valRaw.filter fun d => !isInternalName d && c.isProject d
    let reach := (reachFor c typeRaw).insertMany (reachFor c valRaw)
    let mut termAdd : Std.HashSet Name := {}
    for t in reach do
      unless directTerm.contains t || t == name do termAdd := termAdd.insert t
    for t in sorted termAdd do
      rows := rows.push s!"{render name}\tterm\t{render t}"
  -- Deduplicated after rendering: two private declarations in different modules
  -- can recover to the same user-facing name (`extract` warns about exactly
  -- this), and then they are one row, not two.
  let mut seen : Std.HashSet String := {}
  for r in rows.qsort (· < ·) do
    unless seen.contains r do
      seen := seen.insert r
      IO.println r
