import Lean
open Lean

/-- Histogram: for each *shape* of internal auxiliary constant referenced by a
project declaration, how many project-internal edges does dropping it hide? -/

def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",
  ".mk", ".elim", ".ctorIdx", ".toCtorIdx"
]

def containsSubstring (s sub : String) : Bool := (s.splitOn sub).length > 1

def isInternalName (name : Name) : Bool :=
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  | _             => none

def usedConsts (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants ++ (valueOf ci).elim #[] Expr.getUsedConstants

/-- Bucket an internal name by the syntactic family a fix would have to
recognise. Checked in the order a fix would check them. -/
def shapeOf (n : Name) : String :=
  let last := match Lean.privateToUserName n with
    | .str _ s => s
    | _ => "<non-str>"
  let digitsStripped := last.dropRightWhile Char.isDigit
  if last.startsWith "_proof_" || last.startsWith "proof_" then "_proof_N"
  else if last.startsWith "match_" || last.startsWith "_match_" then "match_N"
  else if last.startsWith "_cstage" then "_cstage"
  else if last == "mk" then ".mk"
  else if last == "casesOn" || last == "recOn" || last == "brecOn"
       || last == "rec" || last == "binductionOn" then ".casesOn/.rec*"
  else if last == "noConfusion" || last == "noConfusionType" then ".noConfusion*"
  else if last == "injEq" || last == "inj" || last == "sizeOf_spec" then ".injEq/.inj"
  else if last == "eq_def" then ".eq_def"
  else if digitsStripped == "eq_" then ".eq_N"
  else if last.startsWith "_" then s!"other _prefixed ({digitsStripped})"
  else s!"other ({digitsStripped})"

structure Ctx where
  env : Environment
  prefixes : Array Name

def Ctx.inTarget (c : Ctx) (n : Name) : Bool :=
  if isInternalName n then false
  else match c.env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match c.env.allImportedModuleNames[idx.toNat]? with
    | none => false
    | some m => c.prefixes.any fun p => m == p || m.toString.startsWith (p.toString ++ ".")

partial def auxClosure (c : Ctx) (n : Name) (acc : Std.HashSet Name) (seen : Std.HashSet Name)
    : Std.HashSet Name × Std.HashSet Name :=
  if seen.contains n then (acc, seen) else
  let seen := seen.insert n
  match c.env.find? n with
  | none => (acc, seen)
  | some ci =>
    (usedConsts ci).foldl (init := (acc, seen)) fun (acc, seen) d =>
      if isInternalName d then auxClosure c d acc seen else (acc.insert d, seen)

def main (args : List String) : IO Unit := do
  initSearchPath (← findSysroot)
  let prefixes := (args.map fun s => s.toName).toArray
  let env ← importModules (prefixes.map fun p => ({ module := p } : Import)) {} (trustLevel := 1024)
  let c : Ctx := { env, prefixes }

  -- per shape: occurrences, project edges hidden, external edges hidden
  let mut occ : Std.HashMap String Nat := {}
  let mut hidProj : Std.HashMap String Nat := {}
  let mut hidExt : Std.HashMap String Nat := {}
  let mut hostsOf : Std.HashMap String (Std.HashSet Name) := {}

  for (name, ci) in env.constants.map₁.toList do
    unless c.inTarget name do continue
    match ci with
    | .ctorInfo _ | .recInfo _ => continue
    | _ => pure ()
    unless (declRangeExt.find? env name).isSome do continue
    let direct := usedConsts ci
    let visible := direct.filter fun d => !isInternalName d
    for a in direct do
      unless isInternalName a do continue
      let sh := shapeOf a
      occ := occ.insert sh ((occ.getD sh 0) + 1)
      let (lost, _) := auxClosure c a {} {}
      let new := lost.toList.filter fun d => !visible.contains d && d != name
      let (p, e) := new.partition c.inTarget
      if !p.isEmpty then
        hostsOf := hostsOf.insert sh ((hostsOf.getD sh {}).insert name)
      hidProj := hidProj.insert sh ((hidProj.getD sh 0) + p.length)
      hidExt := hidExt.insert sh ((hidExt.getD sh 0) + e.length)

  let rows := occ.toList.toArray.qsort fun a b =>
    (hidProj.getD a.1 0) > (hidProj.getD b.1 0)
  IO.println "shape | occurrences | project edges hidden | external edges hidden | distinct hosts"
  for (sh, n) in rows do
    IO.println s!"{sh} | {n} | {hidProj.getD sh 0} | {hidExt.getD sh 0} | {(hostsOf.getD sh {}).size}"
