import Lean
open Lean

/-- Same predicate probe-lean uses to drop auxiliary constants
(`ProbeLean/Analysis.lean:isInternalName`), copied so this script can run
against any toolchain. -/
def autoGeneratedSuffixes : List String := [
  ".noConfusionType", ".noConfusion", ".casesOn", ".rec", ".recOn",
  ".brecOn", ".below", ".ibelow", ".binductionOn",
  ".sizeOf_spec", ".inj", ".injEq",
  ".mk.inj", ".mk.injEq", ".mk.sizeOf_spec",
  ".eq_1", ".eq_2", ".eq_3", ".eq_def",
  ".mk", ".elim", ".ctorIdx", ".toCtorIdx"
]

def containsSubstring (s sub : String) : Bool := (s.splitOn sub).length > 1

def isInternalName (name : Name) : Bool :=
  let name := Lean.privateToUserName name
  let str := name.toString
  str.startsWith "_" ||
  containsSubstring str "._" ||
  containsSubstring str "[" ||
  containsSubstring str "proof_" ||
  containsSubstring str "match_" ||
  name.isInternal ||
  autoGeneratedSuffixes.any fun suffix => str.endsWith suffix

def valueOf : ConstantInfo → Option Expr
  | .defnInfo v   => some v.value
  | .thmInfo v    => some v.value
  | .opaqueInfo v => some v.value
  | _             => none

def usedConsts (ci : ConstantInfo) : Array Name :=
  ci.type.getUsedConstants ++ (valueOf ci).elim #[] Expr.getUsedConstants

def isTheoremLike : ConstantInfo → Bool
  | .thmInfo _ => true
  | _          => false

structure Ctx where
  env : Environment
  prefixes : Array Name

/-- In the target modules and not filtered out by probe-lean, i.e. a constant
that is (or would be) emitted as an atom. -/
def Ctx.inTarget (c : Ctx) (n : Name) : Bool :=
  if isInternalName n then false
  else match c.env.getModuleIdxFor? n with
  | none => false
  | some idx =>
    match c.env.allImportedModuleNames[idx.toNat]? with
    | none => false
    | some m => c.prefixes.any fun p => m == p || m.toString.startsWith (p.toString ++ ".")

/-- Non-internal constants reachable from `n` by passing *only* through internal
auxiliary constants: exactly the edges probe-lean drops. -/
partial def auxClosure (c : Ctx) (n : Name) (acc : Std.HashSet Name) (seen : Std.HashSet Name)
    : Std.HashSet Name × Std.HashSet Name :=
  if seen.contains n then (acc, seen) else
  let seen := seen.insert n
  match c.env.find? n with
  | none => (acc, seen)
  | some ci =>
    (usedConsts ci).foldl (init := (acc, seen)) fun (acc, seen) d =>
      if isInternalName d then auxClosure c d acc seen else (acc.insert d, seen)

def main (args : List String) : IO Unit := do
  let prefixes := (args.map fun s => s.toName).toArray
  initSearchPath (← findSysroot)
  let mods := prefixes.map fun p => ({ module := p } : Import)
  let env ← importModules mods {} (trustLevel := 1024)
  let c : Ctx := { env, prefixes }

  let mut total := 0            -- emitted atoms in target modules
  let mut nonThm := 0           -- of those, not theorems
  let mut withAux := 0          -- reference ≥1 internal aux constant
  let mut loseAny := 0          -- lose ≥1 non-internal edge
  let mut loseTarget := 0       -- lose ≥1 edge to a target-module atom
  let mut gained : Std.HashSet Name := {}   -- target atoms that gain in-degree
  let mut gainedThms : Std.HashSet Name := {}
  let mut lostEdgeCount := 0

  -- in-degree over the graph probe-lean emits (target→target edges only)
  let mut indeg : Std.HashMap Name Nat := {}
  let mut atoms : Array Name := #[]

  for (name, ci) in env.constants.map₁.toList do
    unless c.inTarget name do continue
    match ci with
    | .ctorInfo _ | .recInfo _ => continue
    | _ => pure ()
    unless (declRangeExt.find? env name).isSome do continue
    atoms := atoms.push name
    total := total + 1
    unless isTheoremLike ci do nonThm := nonThm + 1
    let direct := usedConsts ci
    let visible := direct.filter fun d => !isInternalName d
    for d in visible do
      if c.inTarget d then indeg := indeg.insert d ((indeg.getD d 0) + 1)
    let auxes := direct.filter isInternalName
    if auxes.isEmpty then continue
    withAux := withAux + 1
    let mut lost : Std.HashSet Name := {}
    let mut seen : Std.HashSet Name := {}
    for a in auxes do
      let (acc, s) := auxClosure c a lost seen
      lost := acc; seen := s
    let lostNew := lost.toList.filter fun d => !visible.contains d && d != name
    if !lostNew.isEmpty then loseAny := loseAny + 1
    let lostTarget := lostNew.filter c.inTarget
    if !lostTarget.isEmpty then
      loseTarget := loseTarget + 1
      lostEdgeCount := lostEdgeCount + lostTarget.length
      for d in lostTarget do
        gained := gained.insert d
        if let some dci := env.find? d then
          if isTheoremLike dci then gainedThms := gainedThms.insert d

  -- target atoms that are invisible in the emitted graph (in-degree 0) but
  -- would gain an edge once aux closures are folded in
  let mut rescued := 0
  let mut rescuedThms := 0
  for a in atoms do
    if indeg.getD a 0 == 0 && gained.contains a then
      rescued := rescued + 1
      if let some ci := env.find? a then
        if isTheoremLike ci then rescuedThms := rescuedThms + 1

  IO.println s!"modules            : {prefixes.toList}"
  IO.println s!"emitted atoms      : {total} ({nonThm} non-theorem)"
  IO.println s!"reference aux const: {withAux}"
  IO.println s!"lose >=1 edge      : {loseAny}"
  IO.println s!"lose >=1 atom edge : {loseTarget}"
  IO.println s!"dropped atom edges : {lostEdgeCount}"
  IO.println s!"atoms gaining edges: {gained.size} ({gainedThms.size} theorems)"
  IO.println s!"in-degree 0 -> >0  : {rescued} ({rescuedThms} theorems)"
